### ISSUE TITLE
Coder on Caprover One App

### ISSUE THREAD

**Issue by valoricDe** [caprover/one-click-apps#1009]
https://github.com/caprover/one-click-apps/blob/055bf1829466898054d8d84bb86e7aa4d81ec729/public/v4/apps/vscode-coder.yml#L6

@visualfanatic was this ever working?

https://coder.com/docs/v2/latest/install/docker
https://github.com/coder/coder/blob/main/docker-compose.yaml

**Comment by githubsaturn** [comment]
@valoricDe - the image is built on the fly:

https://github.com/caprover/one-click-apps/blob/055bf1829466898054d8d84bb86e7aa4d81ec729/public/v4/apps/vscode-coder.yml#L15-L18

**Comment by valoricDe** [comment]
Ahh, I missed that lines. Thanks :)
