### ISSUE TITLE
App issue: Paperless-ng

### ISSUE THREAD

**Issue by Emilien-Lambert** [caprover/one-click-apps#1049]
Hello, 

I think there's an error in the Paperless-ng configuration. For the "Cookie Prefix" variable, the default value in the one-click app creation form is `$$cap_appname`. We therefore expect the value defined in "App Name" to be used. 

But this doesn't work, and the cookie name is displayed as `$$cap_appnametoken`. 

If possible, we should correct the default value or leave the field empty. 

This problem causes 403 errors for all the actions I try to perform. When I edit the environment variables and change `$$cap_appname` to something like "paperless", everything works fine.

[Initial issue 388](https://github.com/caprover/one-click-apps/pull/388)

**Comment by githubsaturn** [comment]
Fixed, please feel free to comment if the issue still persists.
