### ISSUE TITLE
App Suggestion: BTCPayServer

### ISSUE THREAD

**Issue by deadcoder0904** [caprover/one-click-apps#1050]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

BTCPayServer (self-hosted BTC payment solution)

**Do you know if there is any official Docker image for the app?**

https://github.com/btcpayserver/btcpayserver-docker

Crypto Crowd would love this as BTCPayServer is not available as 1-click app on most (probably all?) self-hosted PaaS. Great marketing angle as well. I even have [a repo](https://github.com/deadcoder0904/btcpayserver-nextjs) if you wanna see how it works. Plus yet another way to fund Caprover through BTC or Lightning payments.

**Comment by osdeverr** [comment]
This would be very helpful. +1

**Comment by coffseducation** [comment]
![image](https://github.com/caprover/one-click-apps/assets/99161534/0ff8ea90-b20a-42a6-8512-bf8e34fa4169)
Present!

**Comment by deadcoder0904** [comment]
didn't know as i couldn't get caprover installed haha. moved over to easypanel.

**Comment by githubsaturn** [comment]
@deadcoder0904 - what issues did you face during the installation?

**Comment by deadcoder0904** [comment]
@githubsaturn i dont remember now but it was very weird. many things didnt work on ubuntu. found out about easypanel but even that didnt work on ubuntu. got it working on debian. might have something to do with docker swarm. or easypanel does something with kernel. it was a clean-slate install but still. using that for now as its very simple but caprover definitely looks more mature & has more support. currently, small-usecase so will just keep it as it is. i'll let you know if i face it again.

**Comment by deadcoder0904** [comment]
@githubsaturn i'm curious if i can install caprover (just for btcpayserver) alongside easypanel. that uses port 80, 443, & 8080 i think.

do i need to do some reverse-proxy stuff like nginx/traefik? im very noob at that.

here's some issue i faced which might be tangential as i tried many different control panels like coolify, caprover, easypanel -> https://stackoverflow.com/questions/77685959/error-for-nginx-bind-for-0-0-0-0443-failed-port-is-already-allocated-while-r & https://unix.stackexchange.com/questions/766733/503-service-temporarily-unavailable-while-using-nginx-traefik-with-easypanel-b

i do remember i couldnt get captain-definition working. i did watch youtube videos & all but just couldnt get it installed. i think it was an installation issue. probably couldnt get caprover install.

**Comment by githubsaturn** [comment]
> i'm curious if i can install caprover (just for btcpayserver) alongside easypanel. that uses port 80, 443, & 8080 i think.

No, they can co-exist as they use the same ports.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/btcpayserver.yml

It looks like it's not updated, but feel free to update.

**Comment by coffseducation** [comment]
> https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/btcpayserver.yml
> 
> It looks like it's not updated, but feel free to update.

Check here for versions: https://hub.docker.com/r/btcpayserver/btcpayserver/tags

**Comment by coffseducation** [comment]
> didn't know as i couldn't get caprover installed haha. moved over to easypanel.

If you do not have Caprover installed and you want to know what is available as well as the versions available, you can always check on the demo site https://captain.server.demo.caprover.com/#/login with password captain42

**Comment by deadcoder0904** [comment]
@githubsaturn @coffseducation that would require significant understanding of docker/devops, right? that looks like a massive yaml file.

or just have to change the version number?

I'm not sure i understand most of it as i just started dipping toes in it. 

cc @ronaldloyko

**Comment by coffseducation** [comment]
> @githubsaturn @coffseducation that would require significant understanding of docker/devops, right? that looks like a massive yaml file.
> 
> or just have to change the version number?
> 
> I'm not sure i understand most of it as i just started dipping toes in it.
> 
> cc @ronaldloyko

That link to Dockerhub is where the Caprover One Click app image is pulled from. (Note the hyperlink in the image below)
When you install the app from Caprover you can specify the version with the tag.
(In the case of complex apps which have databases and other software bundled in you may be best to install the set version then upgrade afterwards)
![image](https://github.com/caprover/one-click-apps/assets/99161534/97bad70a-23e9-4783-8040-805eff854876)
When you upgrade use Deploy method 6. Paste in:
btcpayserver/postgres:13.13
-if that is the version you want. Some apps are best to have incremental upgrades if there are version leaps.

**Comment by deadcoder0904** [comment]
@coffseducation that would only work if the underlying architecture hasn't changed since 2022, right?

if they changed or added new environment variables that are required, it shouldn't work, right? at least theoritically.
