### ISSUE TITLE
App Suggestion: GlitchTip

### ISSUE THREAD

**Issue by iron3oxide** [caprover/one-click-apps#1052]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
GlitchTip is a FOSS Sentry alternative that is compatible with the Sentry SDKs. It is thus very useful for error management and uptime monitoring of web apps.

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/glitchtip/glitchtip

**Comment by wajeht** [comment]
@iron3oxide It's already available `https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/glitchtip.yml`


<img width="1135" alt="image" src="https://github.com/caprover/one-click-apps/assets/58354193/83abee31-61b3-4aef-b457-baa082a1c7b7">

**Comment by iron3oxide** [comment]
Oh nice, must've missed it!
