### ISSUE TITLE
AppWrite Oneclick broken

### ISSUE THREAD

**Issue by hussainsam** [caprover/one-click-apps#1053]
One Click App works fine for the default version but doesn't work with 1.4+ versions. The scheduler service container will not create and start popping up error such as php_network_getaddresses Error.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![image](https://github.com/caprover/one-click-apps/assets/10582082/cd36b663-b5c2-4c16-8358-309bed17ae54)

**Comment by githubsaturn** [comment]
Also keep in mind that the installer for 1.4 might be different. That's why a default version is assigned to each installer. 

The apps are community maintained, please feel free to open a pull request to fix!
