### ISSUE TITLE
Seatable is not using the latest image

### ISSUE THREAD

**Issue by tommerty** [caprover/one-click-apps#1058]
So I found [this PR](https://github.com/caprover/one-click-apps/pull/402) that states that it's gone to the latest version using seatable/seatable-developer, however this is not correct as I just installed using "latest" and it's given me version `2.5.0`, which does not exist seatable/seatable-developer.

See this also: https://github.com/caprover/one-click-apps/pull/402#issuecomment-1203200320

**Comment by githubsaturn** [comment]
The comment just states that these are the changes that need to be made. The original PR is from 2021 and it looks like nobody ever updated that one click app.


If it's so outdated, let me know and I'll remove it from the listing until someone else can modify and update the definition.
