### ISSUE TITLE
Incorrect trust proxy IP for PeerTube one-click-app

### ISSUE THREAD

**Issue by mdavey** [caprover/one-click-apps#107]
The [`PEERTUBE_TRUST_PROXY`](https://github.com/caprover/one-click-apps/blob/dd939bd4a2dee44cf908c6e0ecd86a8d31335a31/public/v2/apps/peertube.json#L48) variable tells PeerTube what hosts it should trust the to provide the real IP of the user.  

I'm unsure what the correct value should be  (I think nginx is `10.0.0.4` but I'm not sure if that is always correct).

I have `PEERTUBE_TRUST_PROXY` set to `[["127.0.0.1", "loopback", "172.18.0.0/16", "10.0.0.0/16"]]` which appears to work correctly.

**Comment by githubsaturn** [comment]
Please feel free to open a PR
