### ISSUE TITLE
App Suggestion: CyberChef

### ISSUE THREAD

**Issue by nileshtrivedi** [caprover/one-click-apps#1077]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

GCHQ has a data transformation toolbox/utility called CyberChef.
Public demo: https://gchq.github.io/CyberChef/
Git Repo: https://github.com/gchq/CyberChef

**Do you know if there is any official Docker image for the app?**

Now it does: https://github.com/gchq/CyberChef/pkgs/container/cyberchef

**Comment by VictorioBerra** [comment]
https://github.com/caprover/one-click-apps/pull/1144
