### ISSUE TITLE
App issue: Updating ZAMMAD

### ISSUE THREAD

**Issue by 0x7466** [caprover/one-click-apps#1078]
The current Zammad one click app does only support up to version 5.2.3 since the zammad docker images for [elasticsearch](https://hub.docker.com/r/zammad/zammad-docker-compose/tags?page=1&name=zammad-elasticsearch) and [postgres](https://hub.docker.com/r/zammad/zammad-docker-compose/tags?page=1&name=zammad-postgres) only got published up to this version.

This is problematic, since [newer versions include security patches](https://zammad.com/en/releases).

It looks like that since version 5.2.3 they don't [build custom images for elasticsearch and postgres](https://github.com/zammad/zammad-docker-compose/releases/tag/v6.0.0) anymore.

**Comment by githubsaturn** [comment]
Hi - sorry for the late response, but apps are community maintained - feel free to find the PRs and comment to notify the contributors. See here: https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md
