### ISSUE TITLE
Suggestion: Hasura

### ISSUE THREAD

**Issue by githubsaturn** [caprover/one-click-apps#11]
Hasura - Instant Realtime GraphQL on Postgres with web admin cosole: https://hasura.io/

**Comment by comontes** [comment]
I have included this in a pull request #36

**Comment by comontes** [comment]
I'm still wondering how to update an app done with this method to the latest version in the future? I was using the Digital Ocean One-Click solution so I used to follow this https://docs.hasura.io/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html#updating-to-the-latest-version

**Comment by githubsaturn** [comment]
According to the docs you shared, you only need to update the image of the container.

```
....
image: hasura/graphql-engine:latest_tag_here
....
```

To do the same thing via CapRover, simply go to the deployment tab of your `hasura/graphql-engine` app, scroll down to captain-definition deployment and copy and paste this:
```
 {
  "schemaVersion": 2,
  "imageName": "hasura/graphql-engine:latest_tag_here"
 }
```

Click on SAVE AND UPDATE button and you're done!

**Comment by githubsaturn** [comment]
See here for details:
https://caprover.com/docs/captain-definition-file.html#use-image-name
