### ISSUE TITLE
Oneclickapp generated list not responding

### ISSUE THREAD

**Issue by GREEB** [caprover/one-click-apps#110]
Hello, regarding the oneclickapps, the list gets pulled from https://oneclickapps.caprover.com/v2/autoGeneratedList.json it seems not to respond atm(12/11/2019 9:55AM GMT). I think it would be good to have a backup locally so that the gui doesn't "break". For now i just get an error "Something bad happened."

Thanks

**Comment by codecanvas-tsegah** [comment]
Hi!
same issue here, is it possible to host the one click apps locally? this would be a nice feature

**Comment by githubsaturn** [comment]
There was a DNS issue, and it's fixed now. We'll make modifications to make this more robust.
