### ISSUE TITLE
App Config choose between different databases

### ISSUE THREAD

**Issue by valoricDe** [caprover/one-click-apps#112]
Hi there,
in Prisma you can currently only choose mysql. But maybe you would like to use postgres.

As I see it we have two options to achieve this:
1. Duplicate the recipe, name it prisma-postgres, done
2. Add a switch/dropdown to choose between two different databases and variable fields.

What do you think about option 2?

**Comment by githubsaturn** [comment]
Option 2 won't be generic enough to for a generic app. We would basically end up with a highly customized element which will be very hard to manage. Imagine a case where based on the drop-down selected value, we have to change other required fields. So the duplication is the way to go in this case.

**Comment by valoricDe** [comment]
Okidok
