### ISSUE TITLE
App issue: Chatwoot

### ISSUE THREAD

**Issue by hnmendes** [caprover/one-click-apps#1135]
### Describe the bug
I've deployed the Chatwoot application using CapRover. The setup seems correct, and HTTPS is functioning. However, when a new agent receives an email to set up their account and clicks on the link, they are redirected to a page showing "Nothing here yet :/" with an invalid SSL certificate warning.

### To Reproduce
1. Deploy Chatwoot on CapRover.
2. Ensure that HTTPS is set up and functioning properly (also tested without https - same thing).
3. Invite a new agent to create an account, which sends an email.
4. Click on the password reset link in the email, e.g., https://mydomain.com/app/auth/password/edit?reset_password_token=userToken

### Expected behavior
The user should be redirected to a secure page where they can reset their password without any SSL certificate errors.

### Platform
Browser

### Additional context
Here is my current NGINX configuration for mydomain.com:

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;
        underscores_in_headers on;
        server_name  <%-s.publicDomain%>;

        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

        <%
        if (s.redirectToPath) {
        %>
            return 302 <%-s.redirectToPath%>;
        <%
        } else {
        %>

            <%
            if (s.httpBasicAuthPath) {
            %>
                auth_basic           "Restricted Access";
                auth_basic_user_file <%-s.httpBasicAuthPath%>; 
            <%
            }
            %>

                proxy_pass $upstream;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

            <%
            if (s.websocketSupport) {
            %>
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
            <%
            }
            %>

        <%
        }
        %>

        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
            root <%-s.customErrorPagesDirectory%>;
            internal;
        }
}
```
### Environment Details
- CapRover version: 1.11.1
- Chatwoot version: 3.11.0
- Server OS: Ubuntu 22.04

### Additional Information
- SSL certificate for mydomain.com was obtained through Let's Encrypt.
- The certificate appears to be correctly configured but results in an invalid certificate error when accessing the reset password link (i.e 404).
- No apparent errors in the NGINX logs or Chatwoot logs relevant to this issue.

**Comment by githubsaturn** [comment]
I just realized that Chatwoot is officially supporting CapRover on [their docs](https://www.chatwoot.com/docs/self-hosted/deployment/caprover). So you should also be able to reach out to their support for help.

**Comment by hnmendes** [comment]
> I just realized that Chatwoot is officially supporting CapRover on [their docs](https://www.chatwoot.com/docs/self-hosted/deployment/caprover). So you should also be able to reach out to their support for help.

Since chatwoot is officially supporting CapRover i'll close this and wait for a response on chatwoot repository.
