### ISSUE TITLE
App issue: MailDev

### ISSUE THREAD

**Issue by RichardAnderson** [caprover/one-click-apps#1140]
### Summary

MailDev single click app stuck in a loop and returning 502 via NGINX.

### Replication Steps:

1. Select "Apps"
2. Select "One-Click Apps/Databases
3. Select MailDev
4. Enter the App Name "MailDev" (can be anything)
5. Enter the MailDev version (either 2.0.5 or latest, same issue)
6. Update the password to be more secure
7. Click Deploy

### Expected Results:

I can access MailDev UI from the browser

### Actual Results

NGINX returns error 502.
Logs report an endless restart loop:

```
srv-captain--maildev.1.bbm1x21n1t0c@localhost    | MailDev using directory /data
srv-captain--maildev.1.bbm1x21n1t0c@localhost    | MailDev webapp running at http://0.0.0.0:1080
srv-captain--maildev.1.bbm1x21n1t0c@localhost    | MailDev SMTP Server running at 0.0.0.0:1025
srv-captain--maildev.1.bbm1x21n1t0c@localhost    | Received shutdown signal, shutting down now...
```

**Comment by githubsaturn** [comment]
Relevant thread: https://github.com/maildev/maildev/issues/484
It looks like it's a problem with MailDev... They should by default bind to IPv4 and IPv6... Probably your system has IPv6 and the default healthcheck fails to detect the health.


Looks like someone suggested a default value of `::` for `MAILDEV_IP` is fixing the problem. I'll make the change and deploy the fix.

**Comment by githubsaturn** [comment]
The one click app is fixed. I just deployed a test instance and confirmed it works. It takes ~10sec to boot up, but it works. 

Please retry and let me know if you are still having problems.
