### ISSUE TITLE
App issue: Invoiceninja install

### ISSUE THREAD

**Issue by coffseducation** [caprover/one-click-apps#1165]
### Installation bugs:
Cannot install the latest version of Invoiceninja [5.10.43](https://github.com/invoiceninja/dockerfiles/releases/tag/5.10.43)

![image](https://github.com/user-attachments/assets/448ae0a9-28d9-45ee-89fa-fde4cd2b0ddb)

**Comment by coffseducation** [comment]
I get this when attempting version [5.10.0](https://github.com/invoiceninja/dockerfiles/releases/tag/5.10.0)

`Failed: Error: {"message":"manifest for invoiceninja/invoiceninja:5.10.0 not found: manifest unknown: manifest unknown"} manifest for invoiceninja/invoiceninja:5.10.0 not found: manifest unknown: manifest unknown`

**Comment by githubsaturn** [comment]
That's because that tag `5.10.0` doesn't exist in Docker Hub:
https://hub.docker.com/r/invoiceninja/invoiceninja/tags?name=5.10.0

For some reason it's called `5.10.0x`

**Comment by githubsaturn** [comment]
You use just use `5.10.43` as it exists:
https://hub.docker.com/r/invoiceninja/invoiceninja/tags?name=5.10.43

**Comment by coffseducation** [comment]
> That's because that tag `5.10.0` doesn't exist in Docker Hub: https://hub.docker.com/r/invoiceninja/invoiceninja/tags?name=5.10.0
> 
> For some reason it's called `5.10.0x`

------------------------- Mon Nov 04 2024 10:27:02 GMT+0000 (Coordinated Universal Time)
Build started for account-app
An explicit image name was provided (invoiceninja:5.10.0x). Therefore, no build process is needed.
Pulling this image: invoiceninja:5.10.0x This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 404) unexpected - pull access denied for invoiceninja, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by coffseducation** [comment]
> You use just use `5.10.43` as it exists: https://hub.docker.com/r/invoiceninja/invoiceninja/tags?name=5.10.43
Hi Kasra.
You can see at the top that 5.10.43 **IS** the version I attempted with the 1 click install - but it failed.
Thank you for pointing to dockerhub for the images though! The documentation from the install points to github. Having the correct tag I was then able to upgrade from 5.9.9 to 5.10.43.

**Comment by githubsaturn** [comment]
In your comment you mentioned use tried 5.10.0... I was confused which one is throwing the error
https://github.com/caprover/one-click-apps/issues/1165#issuecomment-2453637164

Anyways, glad it worked.
