### ISSUE TITLE
Directus uploaded files missing after restart.

### ISSUE THREAD

**Issue by ComputerCarl** [caprover/one-click-apps#118]
![image](https://user-images.githubusercontent.com/29293242/72262002-015e6300-35e4-11ea-93e0-a0b7d3aa7957.png)

I have created a collection in Directus, one of the fields being type of "file". I've inserted a couple of pictures and everything looked OK. The next day I returned to find all images had missing image status as shown above.

I then created a test Directus deployment, created a collection, added a file field and uploaded an image. I restarted the three components of the Directus (app, api, db) using the CapRover "Save & Update" button, and now the image is also missing.

**Comment by ComputerCarl** [comment]
I found an issue of Directus [issue](https://github.com/directus/docker/issues/21) about persisting volumes.

I solved this in my case by re-deploying using a custom captain definition file with changes to the one-click-app Directus code, and adding a volume;
```
{
  "captainVersion": "2",
  "documentation": "Taken from https://github.com/directus/docker.",
  "displayName": "",
  "description": "Directus is an open-source tool for managing content across all your omni-channel digital experiences",
  "dockerCompose": {
    "version": "7",
    "services": {
      "$$cap_appname-db": {
        "image": "mysql:5.7",
	...
      },
      "$$cap_appname-api": {
        "depends_on": {
          "$$cap_appname-db": {
            "condition": "service_healthy"
          }
        },
        "image": "directus/api:2.0.18",
        "volumes": [
          "$$cap_appname-db-uploads:/var/www/html/public/uploads"
        ],
...
```

I see there is also an [option](https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3) for S3 (and Minio) storage, but setting that option in the CD-deployment may be difficult.

**Comment by githubsaturn** [comment]
Thanks! It should be fixed now. Please retry and let me know if the problem still exists.
