### ISSUE TITLE
Starpi redirects to localhost

### ISSUE THREAD

**Issue by Ak4zh** [caprover/one-click-apps#121]
On a fresh installation of strapi, the app deploys well without any errors.
You can open the app main index page which gives you a button to create the first administrator and start using the app.

That button links to http://localhost:1337/admin
(I also tried to open myappURL/admin it returns a HTML page with text `Not Found`)

I see that the template file has HOST environment variable set to "localhost" which may be the reason.
I tried to change my apps environment variable to following values:
```
0.0.0.0
127.0.0.1
app actual url
```

None of above worked.

I additionally tried to redeploy the app using TEMPLATES and changed the HOST value to `$$cap_appname.$$cap_root_domain`
This also outputs the same result.

**Comment by githubsaturn** [comment]
Strapi has now a new docker compose sample at:
https://github.com/strapi/strapi-docker/blob/master/examples/mongo/docker-compose.yml

I've updated the definition to match the new example: https://github.com/caprover/one-click-apps/commit/453eb810ca45c0371c6b22747998a0e30a3999c3

Please test and let me know if it's still causing issues.

**Comment by githubsaturn** [comment]
Nevermind, it's still doing that weird redirect to `localhost`. I manually replaced localhost with the correct URL and things worked well. But regardless the `localhost` issue is a Strapi Docker issue. I filed an issue on their page, we'll see how they fix it...

https://github.com/strapi/strapi-docker/issues/173

**Comment by easaw** [comment]
I noticed that the Strapi issue 173 no longer has the help docs and redirects to v4 help docs home page.

So I thought about it and tried looking for the `.env` file, of which there isn't one.

Anyway, to solve this, on CapRover, install File Browser, go to the strapi data folder and copy the `.env.example` file to `.env` (or just rename it)

Replace `0.0.0.0` with `yourstrapi.subdomain.example.com` and refresh the page, worked great for me.
