### ISSUE TITLE
Suggetion: Discourse

### ISSUE THREAD

**Issue by githubsaturn** [caprover/one-click-apps#13]
https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md
https://github.com/discourse/discourse_docker
https://hub.docker.com/r/discourse/base/

**Comment by sneak** [comment]
I intend to work on this shortly, will send a PR.

**Comment by tehZeno** [comment]
> I intend to work on this shortly, will send a PR.

Have you started working on this ?

**Comment by sneak** [comment]
I did but I ended up finding their existing Docker infrastructure to be a huge mess and began recreating it.  It's not working yet but here's what I've got so far:

https://git.eeqj.de/sneak/discourse-docker

**Comment by githubsaturn** [comment]
This compose config seems pretty neat, if anyone is interested in creating and testing:
https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml

**Comment by ethancedwards8** [comment]
@sneak any progress? I'd be happy to help contribute as I need this also, I have a few ideas, we could use the discourse bitnami image, but use the official sidekiq, redis, and postgresql containers in the docker-compose file

**Comment by sneak** [comment]
No, Discourse ended up being too ajax-heavy for the purpose I intended to use it, and I abandoned my efforts.  This was as far as I got, not sure how useful any of it is (it doesn't work): https://git.eeqj.de/sneak/discourse-docker .  If you undertake the effort and need any help or troubleshooting, drop me a line.

**Comment by ethancedwards8** [comment]
Okay thanks, I think I'll just use the bitnami images, and go from there.

**Comment by ethancedwards8** [comment]
#189 if anyone is viewing this and would like to help then feel free to
