### ISSUE TITLE
App Suggestion: Firefly III

### ISSUE THREAD

**Issue by ckc** [caprover/one-click-apps#138]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Firefly III: a personal finances manager 

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/jc5x/firefly-iii
https://github.com/firefly-iii/firefly-iii

PS.
More better provide some hints about deployment under docker hub or github?

I tried the follow two ways no work:

1. Method 3: Deploy from Github

2.Method 5: Deploy captain-definition file
{ 
"schemaVersion": 2, 
"templateId": "jc5x/firefly-iii" 
}

I got 502

docker logs 

>  #0 /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(33): Illuminate\\Database\\Connectors\\Connector->createConnection('pgsql:host=srv-...', Array, Array)
>     | #4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\PostgresConnector->connect(Array)
>     | #5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
>     | #6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(Object(Closure))
>     | #7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
>     | #8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
>     | #9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect(true)
>     | #10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select count(*)...', Array)
>     | #11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
>     | #12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
>     | #13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
>     | #14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
>     | #15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
>     | #16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
>     | #17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2536): Illuminate\\Database\\Query\\Builder->get(Array)
>     | #18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2464): Illuminate\\Database\\Query\\Builder->aggregate('count', Array)
>     | #19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\\Database\\Query\\Builder->count()
>     | #20 /var/www/firefly-iii/app/Support/FireflyConfig.php(64): Illuminate\\Database\\Eloquent\\Builder->__call('count', Array)
>     | #21 /var/www/firefly-iii/app/Support/System/OAuthKeys.php(61): FireflyIII\\Support\\FireflyConfig->has('oauth_private_k...')
>     | #22 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(72): FireflyIII\\Support\\System\\OAuthKeys::keysInDatabase()
>     | #23 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(96): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->keysInDatabase()
>     | #24 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(54): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->restoreOAuthKeys()
>     | #25 [internal function]: FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->handle()
>     | #26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
>     | #27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
>     | #28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
>     | #29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
>     | #30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
>     | #31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
>     | #32 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
>     | #33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
>     | #34 /var/www/firefly-iii/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #35 /var/www/firefly-iii/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #36 /var/www/firefly-iii/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #39 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #40 {main}
>     | "} 
>     | 
>     | In Connection.php line 669:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known (SQL: select count(*) as aggregate from "  
>     |   configuration" where "name" = oauth_private_key and "configuration"."delete  
>     |   d_at" is null)                                                               
>     |                                                                                
>     | 
>     | In PDOConnection.php line 31:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known                                            
>     |                                                                                
>     | 
>     | In PDOConnection.php line 27:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known                                            
>     |                                                                                
>     | 
>     | Generating new OAuth keys...
>     | Encryption keys generated successfully.
>     | [2020-03-19 03:38:24] local.ERROR: SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to address: Name or service not known (SQL: insert into "oauth_clients" ("user_id", "name", "secret", "redirect", "personal_access_client", "password_client", "revoked", "updated_at", "created_at") values (?, FireflyIII Personal Access Client, FdxjlFJ5k7KHoAFcFLOQfvZt1HPxX82WavEyaEWP, http://localhost, 1, 0, 0, 2020-03-19 03:38:24, 2020-03-19 03:38:24) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 7): SQLSTATE[08006] [7] could not translate host name \"srv-captain--pgsql\" to address: Name or service not known (SQL: insert into \"oauth_clients\" (\"user_id\", \"name\", \"secret\", \"redirect\", \"personal_access_client\", \"password_client\", \"revoked\", \"updated_at\", \"created_at\") values (?, FireflyIII Personal Access Client, FdxjlFJ5k7KHoAFcFLOQfvZt1HPxX82WavEyaEWP, http://localhost, 1, 0, 0, 2020-03-19 03:38:24, 2020-03-19 03:38:24) returning \"id\") at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
>     | [stacktrace]

New to container, any solution or hints?

Thanks

**Comment by ckc** [comment]
docker logs 

>  #0 /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('pgsql:host=srv-...', 'cap_pg_user', 'secret_firefly_...', Array)
>     | #3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(33): Illuminate\\Database\\Connectors\\Connector->createConnection('pgsql:host=srv-...', Array, Array)
>     | #4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\PostgresConnector->connect(Array)
>     | #5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
>     | #6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(Object(Closure))
>     | #7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
>     | #8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
>     | #9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect(true)
>     | #10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select count(*)...', Array)
>     | #11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
>     | #12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
>     | #13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
>     | #14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
>     | #15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
>     | #16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
>     | #17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2536): Illuminate\\Database\\Query\\Builder->get(Array)
>     | #18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2464): Illuminate\\Database\\Query\\Builder->aggregate('count', Array)
>     | #19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\\Database\\Query\\Builder->count()
>     | #20 /var/www/firefly-iii/app/Support/FireflyConfig.php(64): Illuminate\\Database\\Eloquent\\Builder->__call('count', Array)
>     | #21 /var/www/firefly-iii/app/Support/System/OAuthKeys.php(61): FireflyIII\\Support\\FireflyConfig->has('oauth_private_k...')
>     | #22 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(72): FireflyIII\\Support\\System\\OAuthKeys::keysInDatabase()
>     | #23 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(96): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->keysInDatabase()
>     | #24 /var/www/firefly-iii/app/Console/Commands/Integrity/RestoreOAuthKeys.php(54): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->restoreOAuthKeys()
>     | #25 [internal function]: FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->handle()
>     | #26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
>     | #27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
>     | #28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
>     | #29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
>     | #30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
>     | #31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
>     | #32 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
>     | #33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
>     | #34 /var/www/firefly-iii/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #35 /var/www/firefly-iii/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #36 /var/www/firefly-iii/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #39 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
>     | #40 {main}
>     | "} 
>     | 
>     | In Connection.php line 669:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known (SQL: select count(*) as aggregate from "  
>     |   configuration" where "name" = oauth_private_key and "configuration"."delete  
>     |   d_at" is null)                                                               
>     |                                                                                
>     | 
>     | In PDOConnection.php line 31:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known                                            
>     |                                                                                
>     | 
>     | In PDOConnection.php line 27:
>     |                                                                                
>     |   SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to a  
>     |   ddress: Name or service not known                                            
>     |                                                                                
>     | 
>     | Generating new OAuth keys...
>     | Encryption keys generated successfully.
>     | [2020-03-19 03:38:24] local.ERROR: SQLSTATE[08006] [7] could not translate host name "srv-captain--pgsql" to address: Name or service not known (SQL: insert into "oauth_clients" ("user_id", "name", "secret", "redirect", "personal_access_client", "password_client", "revoked", "updated_at", "created_at") values (?, FireflyIII Personal Access Client, FdxjlFJ5k7KHoAFcFLOQfvZt1HPxX82WavEyaEWP, http://localhost, 1, 0, 0, 2020-03-19 03:38:24, 2020-03-19 03:38:24) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 7): SQLSTATE[08006] [7] could not translate host name \"srv-captain--pgsql\" to address: Name or service not known (SQL: insert into \"oauth_clients\" (\"user_id\", \"name\", \"secret\", \"redirect\", \"personal_access_client\", \"password_client\", \"revoked\", \"updated_at\", \"created_at\") values (?, FireflyIII Personal Access Client, FdxjlFJ5k7KHoAFcFLOQfvZt1HPxX82WavEyaEWP, http://localhost, 1, 0, 0, 2020-03-19 03:38:24, 2020-03-19 03:38:24) returning \"id\") at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
>     | [stacktrace]

**Comment by ckc** [comment]
It's ok, just ignored db config earlier
just add if still feel this app practical 
thanks

**Comment by githubsaturn** [comment]
Let's keep this open as I think it's a good app.

**Comment by jacquant** [comment]
Related PR #217
