### ISSUE TITLE
Firefox websocket issues  with hasura subscriptions.

### ISSUE THREAD

**Issue by clementvp** [caprover/one-click-apps#141]
I'm using the Hasura one click app (a graphql server), with graphql subscription (over websocket).

The websocket support is enable on the dashboard app.

I'm able to perform subscriptions (with appol-graphql) with Chrome and everything works like a charm.
BUT in Firefox the browser console say it can't establish a connexion at the ws adress.

I try installing just a fresh hasura on a digital ocean droplet and everything work out of the box (both on chrome and firefox). But when i install Hasura on a Caprover instance (tried on 3 dedicated server), everytime i ran into this weird behavior with subscriptions.

I repeat myself the websocket support is enable on the app dashboard.

Maybe a Nginx configuration to add ? (I'm noob with nginx). A bug in Firefox ?

**Comment by githubsaturn** [comment]
Duplicate of https://github.com/caprover/caprover/issues/643
