### ISSUE TITLE
App Suggestion: Outline

### ISSUE THREAD

**Issue by ckc** [caprover/one-click-apps#145]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
https://github.com/outline/outline

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/outlinewiki/outline

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/commit/1ec46526f8dd4c65e5447b9af0b2cf4f904e124d
