### ISSUE TITLE
One Click Apps Update

### ISSUE THREAD

**Issue by AngeloReppucci** [caprover/one-click-apps#146]
Hi to all,

excuse me if this is not the right place do ask this, but i was unable to find good answers over internet. 
What is the best practices to update an already installed one click app to a major version?

Thanks to everybody.

**Comment by githubsaturn** [comment]
It really depends on the type of app that you want to update. You can find better answers by searching through the forums related to that particular app or StackOverflow. 


Some apps have internal update mechanism. For example when you want to update WordPress application all you need to do is to navigate your admin settings, and click on update WordPress.

Some other applications don't have built-in update mechanisms. Usually these apps need to be redeployed. For example when you want to update a MySQL container, all you need to do is to deploy a newer version of that image. Navigate to deployments tab in CapRover and deploy from a docker file:
```
FROM mysql:latest
```
And done. 

Your data will be preserved.


The important thing to consider is that the updated strategy really depends on the application.
