### ISSUE TITLE
App Suggestion: Mailtrain

### ISSUE THREAD

**Issue by Toumaniere** [caprover/one-click-apps#147]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Mailtrain: [https://mailtrain.org/](https://mailtrain.org/)
GIthub: [https://github.com/Mailtrain-org/mailtrain](https://github.com/Mailtrain-org/mailtrain)
**Do you know if there is any official Docker image for the app?**
Yes, _osixia/mailtrain:v1.24.1_

**Comment by jacquant** [comment]
The PR #216
