### ISSUE TITLE
Failed: Error: Push failed: Error: (HTTP code 500) server error - invalid reference format

### ISSUE THREAD

**Issue by raj457036** [caprover/one-click-apps#153]
i am getting this error for one click app. normal app creation is working. app from my private registry working. 

but for one click app or from template getting this error

![image](https://user-images.githubusercontent.com/19155680/79800326-a32ae400-8379-11ea-81f2-3f24e630841a.png)

**Comment by githubsaturn** [comment]
@raj457036 

Do you have self-hosted registry enabled? Can you disable that and try again?

**Comment by raj457036** [comment]
Does that affect one click app?

Okay i will try

**Comment by githubsaturn** [comment]
It does not, but the error you're seeing seems to be related to that. All you need to do is to disable `push`:
![Uploading image.png…]()

**Comment by raj457036** [comment]
Humm... Thanks that work perfectly.
