### ISSUE TITLE
Suggestion: gitea

### ISSUE THREAD

**Issue by githubsaturn** [caprover/one-click-apps#16]
https://github.com/go-gitea/gitea

**Comment by GregaVrbancic** [comment]
Hi!

I have tried to create [a template for Gitea](https://github.com/GregaVrbancic/one-click-apps/blob/gitea-template/public/v1/apps/gitea.json). Please feel free to test it out and give recommendations for possible improvements, bugfixes, etc.

**Comment by githubsaturn** [comment]
Looks good! Have you tested this yourself?


I'll give it a shot in day or two.

**Comment by GregaVrbancic** [comment]
I have tested this, but just briefly. At first sight, it looks that everything is working, but I will do some more in-depth testing later today or tomorrow and will report back.

**Comment by githubsaturn** [comment]
@GregaVrbancic 

Looks great!

Maybe just add a section in `instructions.end` mentioning something along these lines:

Since Gitea is running inside a container, you can optionally map a port (not-22) of host to port 22 of the container if you want to use git command over SSH. You can perform port mapping in your CapRover dashboard, in App Configs section. 


Let's add this and create a PR!

**Comment by GregaVrbancic** [comment]
I have also tested it out more in-depth and everything works as expected. I will create PR right away.
