### ISSUE TITLE
Gitea OCA doesn't expose SSH port

### ISSUE THREAD

**Issue by piedoom** [caprover/one-click-apps#169]
I noticed that cloning from SSH kept failing on my Gitea one-click. I mapped `22:22` and everything seemed like it was fixed. I haven't looked into app templates but if I do I might be able to help with this one if it is indeed a port issue.

**Comment by githubsaturn** [comment]
@piedoom 
That's expected. One click apps by default don't assume any particular configuration. Users have the option to adjust the apps to suite their needs. The SSH port is an example of this.

**Comment by githubsaturn** [comment]
Also, be very careful with port 22 mapping. If your server is already using port 22 for SSH, then you might block SSH to your server by mapping to port 22. It's better to use a different port. e.g., map port `1234` of the host to `22` of the container.
