### ISSUE TITLE
App Suggestion: Mastodon

### ISSUE THREAD

**Issue by rymdluo** [caprover/one-click-apps#200]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Twiiter alternative Mastodon: https://github.com/tootsuite/mastodon

**Do you know if there is any official Docker image for the app?**
Dockerfile: https://github.com/tootsuite/mastodon/blob/master/Dockerfile
Compose: https://github.com/tootsuite/mastodon/blob/master/docker-compose.yml

**Comment by lisaiceland** [comment]
How do I add an admin user?

**Comment by somnathrakshit** [comment]
I am having troubles sending confirmation email while creating an account from the web UI

**Comment by nghialele** [comment]
> 

Please provide more details in what you mean "troubles". 
Or at least put in a copy of the log where the error was logged.

I suppose you are having issues with SMTP mail server. Are you managed to solve it?

**Comment by maietta** [comment]
This is an ongoing issue as of today, Dec 22.

This must be a configuration problem and the provided One-Click-App needs further tweaking to be correct.
