### ISSUE TITLE
App Suggestion: Jellyfin

### ISSUE THREAD

**Issue by vohzd** [caprover/one-click-apps#201]
Open source alternative to Plex.

I've already installed this manually, but I'm raising an issue to remind myself to create this as a one-click app.

Official Docker image here: https://hub.docker.com/r/jellyfin/jellyfin/

**Comment by dramikei** [comment]
Hey, I was interested in installing Jellyfin. If you're near completion then please let me know. Otherwise, I may be interested in creating (my first) one-click-app for this :)
