### ISSUE TITLE
Poste.io not running

### ISSUE THREAD

**Issue by olla-dev** [caprover/one-click-apps#220]
I tried to install Poste.io but after the install, no logs whatsoever are showing?

the domain name is something like this: mail.mydomain.com

any ideas on how to find out the reason ?

thank you

**Comment by vohzd** [comment]
Hello, is there anything in the Docker logs themselves?

Firstly, does running `docker ps -a` from a SSH session on your machine show poste.io as exited/stopped?

Then Find out it's container name and run `docker logs ID_HERE` and see if there's anything useful in there.

**Comment by vohzd** [comment]
To sanity check, I've just given this a test on my CR instance to see if I get anywhere. I can get both server logs and after installing get the app to open the `initial server configuration` page which says to me it's working.

Here's my steps;

- Select poste.io one click app.
- Deploy wait a minute or two.
- Enable SSL + force to SSL
- Paste in the predeploy script given here;
```
Please paste the preDeployFunction from https://github.com/caprover/caprover/issues/479#issuecomment-520902309 to the App Config > Pre-Deploy section of your created poste.io instance test.
```
- Wait a few minutes (you'll get a 502 before then).
- Open URL get to initial server config page.

**Comment by m4200** [comment]
thank you, 

I started on a fresh install of caprover. installed the poste.io app. named it mail 
the app does show in the list of apps in caprover

but docker ps -a | grep srv-captain--mail
gives nothing (empty results)

**Comment by githubsaturn** [comment]
@m4200 what's the output of `docker ps -a `

**Comment by m4200** [comment]
hello,

it shows only caprover containers (certbot, caprover). the poste.io container does not show

**Comment by githubsaturn** [comment]
@m4200 you most probably have a server issue - like a disk or etc.

What's the output of `docker service ls` ?

**Comment by nmitra6** [comment]
I am also facing similar problem after installing strapi.io and forcing https. strapi admin and postgres containers are running but webui get list is showing only initial containers.
docker ps and docker service ls and docker logs are absolutely fine

**Comment by murfasa** [comment]
I'm facing a problem getting poste.io running using one-click. I have a installation that follows the recommended settings yet I'm left with 3 exited docker containers and logs that show:
`2023-06-02T02:18:55.050652505Z exec /init: exec format error
2023-06-02T02:19:01.094038844Z exec /init: exec format error
2023-06-02T02:19:07.235460108Z exec /init: exec format error
2023-06-02T02:19:13.257730907Z exec /init: exec format error`
I have set the pre-deploy script in addition to the Nginx config properly and I'm still receiving a 502 error.
I'm running an aarch64 virtual machine on Ubuntu 20.04 LTS. What am I missing?

**Comment by githubsaturn** [comment]
@murfasa  - very likely poste.io image is only for amd64.
