### ISSUE TITLE
typo in generated URL

### ISSUE THREAD

**Issue by m4200** [caprover/one-click-apps#224]
In parse app generated by caprover, there is a small typo : parse-dashbaord instead of parse-dashboard

**Comment by githubsaturn** [comment]
Thanks, fixed!

**Comment by m4200** [comment]
great thank you ! 
how do we change the URL of an app already deployed to correct the typo?

**Comment by githubsaturn** [comment]
You can rename your apps by clicking on the pen icon next to your app name
![image](https://user-images.githubusercontent.com/10582082/87833173-76da1300-c855-11ea-8490-c3601934f898.png)

Be careful! This can cause problems if it's a production app, connections to other apps might break
