### ISSUE TITLE
Suggestion: Invoice Ninja

### ISSUE THREAD

**Issue by fi0** [caprover/one-click-apps#23]
https://github.com/invoiceninja/dockerfiles

**Comment by julianengel** [comment]
I would 100% second that! Going to try and install today manually actually!

**Comment by fi0** [comment]
#103

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/pull/406

**Comment by nsomaru** [comment]
Hi there,

I'm trying to understand what crashes InvoiceNinja causes, and how they can be mitigated? I would like to run IN inside CR.

**Comment by githubsaturn** [comment]
There are a few comments linked to the commit that removes invoice ninja
