### ISSUE TITLE
App Suggestion: Moodle

### ISSUE THREAD

**Issue by joe7ean** [caprover/one-click-apps#242]
Moodle is a learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments. 

https://moodle.org
https://github.com/moodle/moodle
https://hub.docker.com/r/bitnami/moodle/

**Comment by flaviobarros** [comment]
Any update?

**Comment by amjed-ali-k** [comment]
> 
> 
> Any update?

I made a one-click-app image and uploaded here #450 . If it is merged, Moodle LMS will be available.

**Comment by JohnTrabusca** [comment]
unfortunately this doesn't work causing assets to error 500

**Comment by coffseducation** [comment]
Hello! Is Moodle working?

**Comment by githubsaturn** [comment]
Feel free to open a pull request. There are a few things that needs to be changed but overall, if it works, it's great!
By the way, for the main repo, we should use the official image. Due to security risk, we cannot accept personal forks

**Comment by githubsaturn** [comment]
It's unfortunate that Moodle does not offer an official image. Looking at your repository, I don't understand why they don't host that themselves. Have you opened an issue with them?

PS: regarding the personal repositories - I understand this is frustrating, but it's just there to keep everyone a bit safer.

**Comment by EsdrasCaleb** [comment]
They have one but its for development I will open an Inssue there and link my repo. Thx

**Comment by EsdrasCaleb** [comment]
Sadly, I guess my app will never be accepted, they have 0 priorities in providing something like this:
https://moodle.org/login/index.php?loginredirect=1

Why was Bitnani acceptable again?
