### ISSUE TITLE
Invalid variable RAIL_ENV in Chatwoot one-click configuration

### ISSUE THREAD

**Issue by mattes3** [caprover/one-click-apps#245]
There are two typos in the configuration file for the one-click app "Chatwoot":

https://github.com/caprover/one-click-apps/blob/af172b6680583487bdeacf230d7abaf9b57f4811/public/v4/apps/chatwoot.yml#L28

https://github.com/caprover/one-click-apps/blob/af172b6680583487bdeacf230d7abaf9b57f4811/public/v4/apps/chatwoot.yml#L48

It must be `RAILS_ENV` instead of RAIL_ENV.

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/pull/247
