### ISSUE TITLE
Support for build key in services map

### ISSUE THREAD

**Issue by MrSquaare** [caprover/one-click-apps#248]
Allow to use an existing Dockerfile instead of an image 
Reference: https://docs.docker.com/compose/compose-file/#build

NB: In version 2 of the schema, it was possible to use it, I don't know if this is the case in version 4. If so, how to do it?

**Comment by githubsaturn** [comment]
You can use `dockerfileLines` property. Here is an example:
https://github.com/caprover/one-click-apps/blob/af172b6680583487bdeacf230d7abaf9b57f4811/public/v4/apps/minio.yml#L13-L15
