### ISSUE TITLE
Nextcloud One-Click-App : Cron container isn't working

### ISSUE THREAD

**Issue by Ratatinator97** [caprover/one-click-apps#255]
Firstly I want to thank you all for this amazing job :) 
I have a fresh install of the Nextcloud one-click-app and the cron container isn't working properly.
I have this msg error : \
![cron_nextcloud](https://user-images.githubusercontent.com/45072484/91161894-a9382500-e6cb-11ea-8ba9-6a48564f0ff4.png)\
I have installed the `production` version of the dockerised Nextcloud.

Another thing I can't configure is the NGINX config for the nexcloud app.
Problem is that when I add the lines \
`add_header Strict-Transport-Security max-age=15552000; `and `includeSubDomains" always;` it crashes the caprover server and I have to reset all the custom NGINX configs.

Thanks

**Comment by githubsaturn** [comment]
> I have installed the production version of the dockerised Nextcloud.

What do you mean by "production" version?

> add_header Strict-Transport-Security max-age=15552000; and includeSubDomains" always; it crashes the caprover server and I have to reset all the custom NGINX configs.

his should be only one line:
```
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
```

Also where are you adding this line?

**Comment by Ratatinator97** [comment]
I use the docker tagged as "production" which corresponds to the 17.0 version of nextcloud

My bad, I thought it was sliced in two lines as there was semicolons... Thx

**Comment by githubsaturn** [comment]
I am not sure if it's related, but the default version is 19. And I think most people who submit one click app tests with that version.

**Comment by githubsaturn** [comment]
Also, keep in mind that:
- One click apps are community maintained.
- And they are nothing more than Docker Compose. So if there is any issues with the docker compose definition - I suggest you reach out to NextCloud folks and ask them why it's not working.

**Comment by Ratatinator97** [comment]
Okay, thanks for the advise :) I'll update you if I find something usefull !

**Comment by Ratatinator97** [comment]
I installed the latest ( at this time 19.0 ) version and the cron works properly :+1:
