### ISSUE TITLE
App Suggestion: Invoice Plane

### ISSUE THREAD

**Issue by edcous** [caprover/one-click-apps#261]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
InvoicePlane is a self-hosted open source application for managing your quotes, invoices, clients and payments.

https://www.invoiceplane.com/

**Do you know if there is any official Docker image for the app?**
There is no official docker but they link to some on downloads: https://www.invoiceplane.com/downloads

**Comment by Brandutchmen** [comment]
@edcous I might get around to trying to add this one. I've used invoice plane in the past and it would make a great addition to CapRover

**Comment by edcous** [comment]
I’ve been trying to deploy it and have had some trouble, so a one click app would be awesome. Have you personally deployed it?

**Comment by Brandutchmen** [comment]
I have deployed it outside of caprover before. I am working on a one click app atm.

What issues were you running into while deploying this?

**Comment by edcous** [comment]
Well there isn’t an official docker image, so I was having trouble with certain ones. Once you have the template for a one click app I can use please let me know ❤️

**Comment by edcous** [comment]
Were you able to get any work done on this?

**Comment by thomascenni** [comment]
@edcous , @Brandutchmen 
We are adding InvoicePlane right now, see https://github.com/caprover/one-click-apps/pull/296
If you want to test before being officially in the repository, you can find the template [here](https://github.com/thomascenni/alpine-invoiceplane/blob/master/invoiceplane.yml).

**Comment by kgnfth** [comment]
i think this issue can be closed.
