### ISSUE TITLE
Portainer not deploying properly

### ISSUE THREAD

**Issue by WillCMcC** [caprover/one-click-apps#266]
When I one click deploy Portainer, I get 502 errors when trying to access the web UI. I have tried this on 2 different deployments of Caprover, both I am able to access other applications without issues.

![Screen Shot 2020-09-17 at 11 45 05 AM](https://user-images.githubusercontent.com/7244885/93513949-6ee13280-f8db-11ea-8327-5bea2c2d6024.png)
![Screen Shot 2020-09-17 at 11 44 54 AM](https://user-images.githubusercontent.com/7244885/93513951-6f79c900-f8db-11ea-9108-63793bb95e70.png)

**Comment by WillCMcC** [comment]
Ah I was able to get a successful deploy by changing the version. I will submit a PR to update the default after work 👍

**Comment by githubsaturn** [comment]
Thanks for reporting. Version is updated, please report back if it's still showing issues.

**Comment by WillCMcC** [comment]
@githubsaturn 🙏  you're a hero, thank you for the work you do!
