### ISSUE TITLE
Should README be updated?

### ISSUE THREAD

**Issue by DamodarSojka** [caprover/one-click-apps#281]
As per https://github.com/caprover/caprover/issues/786 the README instructions seem not to be up to date any more. The file doesn't have to be in JSON format, given that my build fails anyway I am not sure.

**Comment by githubsaturn** [comment]
It is up to date. Why do you think it's not?
![image](https://user-images.githubusercontent.com/10582082/95681370-72e83380-0bad-11eb-9abf-16f244b5f4e6.png)

**Comment by DamodarSojka** [comment]
I must have somehow ended on a permalink to an old version. Sorry about that!
