### ISSUE TITLE
How to update the caprover apps created by one click apps?

### ISSUE THREAD

**Issue by devxpy** [caprover/one-click-apps#286]
Hey, I love caprover's one click apps, but I can't figure out how to update the app after I've deployed a one click app. Deleting the app and re-creating does not seem like a sane way to do this...

Background - I need to make some edits to the Dockerfile of the sentry app, but I have an instance running in production, so directly editing the [yml config](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/sentry.yml) is not an option

**Comment by githubsaturn** [comment]
CapRover one click apps are just docker instances after deploy. You can update them like how you do so for a Docker image. You can typically deploy a new Dockerfile via the deployment tab.

**Comment by githubsaturn** [comment]
Just write your new Dockerfile and deploy it:
```
FROM sentry:9.1.0
RUN echo 'auth.allow-registration: false' > /etc/sentry/config.yml
......
.......
```
