### ISSUE TITLE
Improvement: App Updates

### ISSUE THREAD

**Issue by DavidSteinbauer** [caprover/one-click-apps#297]
I installed an app with the one-click-setup.

Now there has been a new Version released and I would like to update.

I can not just use the app deployment settings by pulling the new image from docker hub because, the one-click-app has some intelligent script behind it.

Therefore we need the possibility to re-deploy the app by editing the initial variable page and change the version in there.
After that the app should remove the docker-containers (without persistent volumes) and bring the container up with the latest variables (and therefore with the latest docker image).

Would that be possible?

**Comment by DavidSteinbauer** [comment]
@pranavrajs this should be manually settable otherwise I have to do it again and again: https://github.com/caprover/one-click-apps/pull/291/commits/ccd4a9408b0c1864d79efc953cf15ab8c9b71a9d

or how do I make an update to the app *after* installation

**Comment by pranavrajs** [comment]
@DavidSteinbauer For Chatwoot, we have a guide for upgrading the installation without much trouble. I'm not sure whether this can be done at Caprover level (I hope that's what you are suggesting) because each app would have different scripts to run.

https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-caprover#upgrading-chatwoot-installation

**Comment by githubsaturn** [comment]
Yes, this script above will work fine. 

@pranavrajs - I suggest you change your documentation to use method 4 - which is plain Dockerfile content and it's much easier to read/modify:
![image](https://user-images.githubusercontent.com/10582082/98249855-bd5a9700-1f44-11eb-9bef-3e3cf2f2f49d.png)


@DavidSteinbauer - to your point, unfortunately not all apps have the same upgrade process. 
- Some apps can be upgrade simply by deploying a new image (like PhpMyAdmin for example)
- Some apps require a new Dockerfile to be updated (like Chatwoot)
- Some apps can be upgraded internally (like wordpress)
- Some apps needs to be upgraded internally and the image also needs to be upgrade (like wordpress if minimum php version is increased)
- Some apps require manual data migration before upgrading the image (like Postgres when they introduce a breaking change)
- and many more... 

I can't think a generalized way to upgrade all apps. In fact, it WILL cause more harm than good. It might break apps and etc.

**Comment by DavidSteinbauer** [comment]
@prabirshrestha @githubsaturn Thanks! okay that helps.
