### ISSUE TITLE
Suggestion: Sentry

### ISSUE THREAD

**Issue by nephthys** [caprover/one-click-apps#30]
https://sentry.io

https://hub.docker.com/_/sentry
https://github.com/getsentry/onpremise

**Comment by MeXaaR** [comment]
That would be really cool to have sentry, I agree

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/pull/60

**Comment by terehov** [comment]
I was wondering if that's the correct docker image since there have been no updates for a year or so. 
I believe the actual one is: https://hub.docker.com/r/getsentry/sentry
