### ISSUE TITLE
App Suggestion: Node.JS & Django

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/one-click-apps#304]
I would love to be able to choose Node.JS & Django containers for my back-end, which will fetch the source code from GitHub/BitBucket/GitLab and have my custom app up & running, Heroku style.

Docker container is available for all of them.

**Comment by githubsaturn** [comment]
There is no need for a one click app. These are just regular apps that you can deploy!

To see an example:
- Download a tar file of your choice from [here](https://github.com/caprover/caprover/tree/master/captain-sample-apps)
- DO NOT untar the file.
- Create a new app on your apps dashboard.
- Navigate to deployment tab
- And just upload the tar file directly to your CapRover
![image](https://user-images.githubusercontent.com/10582082/99887157-dd11e080-2c0f-11eb-86f7-93a37c2ad48f.png)

**Comment by alexander-potemkin** [comment]
Thank you! Yes, I figured that out, but having sample app running inside, just saying hello world, as a starter, would be much more intuitive and easy to follow, from my perspective.
