### ISSUE TITLE
App Suggestion: [mailcow]

### ISSUE THREAD

**Issue by sitolux** [caprover/one-click-apps#308]
**I'd like to see the MAILCOW DOCKERIZED project in CapRover as a one-click app.**
It has a beautiful web based control panel and gives the users a excellent dashbord for monitoring and administration of the system and getting things done .

**Do you know if there is any official Docker image for the app?** 
git clone https://github.com/mailcow/mailcow-dockerized
more info about config in english https://www.bennetrichter.de/en/tutorials/mailcow-dockerized/
in german https://www.bennetrichter.de/anleitungen/mailcow-dockerized/

**Comment by kgnfth** [comment]
I think that's not possible as a oneclick app because it needs the data folder https://github.com/mailcow/mailcow-dockerized/tree/master/data

its better to deploy mailcow on a seperate server like i do

**Comment by xXKynarethXx** [comment]
CapRover already has poste.io - if you didn't see that already :)

**Comment by kaaax0815** [comment]
I found that poste.io is very weird, and mailcow seems like a way better alternative. i am currently running a mailserver on the host, but a good gui and stuff would be cool.
+1

**Comment by Ak4zh** [comment]
Quoting a 2 years old reply by Kasra on mailcow app request:

```
On top of having a very complicated docker-compose, it seems to require direct access to Port 80 and port 443. This creates a conflict between the nginx that kept river runs and mailcow. At the very least because of this conflict, you cannot run this application on the same server as caprover.
If somehow this conflict could be resolved by replacing the target ports to an unused ones, theoretically one could deploy this on the same server. You would simply follow the same steps as their tutorial and deployed on the same server. Because caprover is non intrusive, it will not touch the services that it has not created. So they can coexist peacefully.
Another approach is to use another GUI for docker, like Portrainer. It is available as a one-click app on CapRover. Portrainer is similar to CapRover, however, it's a pure docker GUI without its internal management of services and apps like CapRover. I suggest you check it out if you want to deploy more complicated docker recipes.
```

**Comment by sitolux** [comment]
I will try to run portainer and check if nginx can handle it 👍 Thank you for checking this
