### ISSUE TITLE
How to deploy Strapi from a local machine?? [Question]

### ISSUE THREAD

**Issue by IvanCoronado** [caprover/one-click-apps#347]
I have deployed the strapi-postgress one-click-app on my server successfully. Now I would like to push my code from my local or Github repo but I get this error `Captain Definition file does not exist!` when I use `caprover deploy`.

![image](https://user-images.githubusercontent.com/13351933/104558635-690a1c80-5643-11eb-9189-d3a588342260.png)

Where can I get this file?

Thank you in advance.

**Comment by githubsaturn** [comment]
One click apps are community maintained. I am not sure about the development flow with Strapi. 

But in general, one click apps are equivalent of `apt install someapp` or `brew install node`... You don't "deploy" code over a one click app once it's created. 

Specifically, Strapi one click app is just a wrapper for Strapi Docker image: https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/strapi-postgres.yml#L6

I'd suggest you reach out to Strapi community to get clarification on this. 


PS: this is a wild guess, but from the looks of Strapi, it appears that it's a no-code CMS. If you want to deploy a frontend application that uses Strapi as a backend, you need to have a Dockerfile that serves your static content. If you have an example for the repo that you're trying to deploy, please share and I can help you out.

**Comment by IvanCoronado** [comment]
I have finally added this Dockerfile to the project https://github.com/strapi/strapi-docker/blob/master/examples/custom/Dockerfile to my repo. Now after running `caprover deploy` the server is able to rebuild the Strapi instance with my changes.

Thanks @githubsaturn
