### ISSUE TITLE
App Suggestion: Seatable (airtable alternative)

### ISSUE THREAD

**Issue by ariaseta** [caprover/one-click-apps#363]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
It's an awesome opensource alternative to airtable

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/seatable/seatable

https://manual.seatable.io/docker/Developer-Edition/Deploy%20SeaTable-DE%20with%20Docker/

**Comment by olragon** [comment]
Follow #402
