### ISSUE TITLE
Sentry, GITHUB and SLACK integration

### ISSUE THREAD

**Issue by lupu60** [caprover/one-click-apps#387]
Slack integration is not working.
<img width="510" alt="Screen Shot 2021-04-16 at 09 47 22" src="https://user-images.githubusercontent.com/5337610/114982987-601e2680-9e90-11eb-8fd7-91f037854485.png">

When I try to add GitHub I'm encountering this err:
https://github.com/getsentry/sentry/issues/12670

And I don't really know how to fix it

**Comment by DestinTech** [comment]
Has this been fixed?

**Comment by lupu60** [comment]
Hey, I don't know. :D
