### ISSUE TITLE
App Suggestion: [baserow]

### ISSUE THREAD

**Issue by ak4zh** [caprover/one-click-apps#400]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Baserow is an open source online database tool and _Airtable alternative_. Create your own database without technical experience. Our user friendly no-code tool gives you the powers of a developer without leaving your browser.

**Do you know if there is any official Docker image for the app?**
_Docker Image:_ https://hub.docker.com/r/tiredofit/baserow
_Docker Compose:_ https://gitlab.com/bramw/baserow/-/blob/develop/docker-compose.yml
_Repository:_ https://gitlab.com/bramw/baserow

**Comment by LiquidITGuy** [comment]
flag for follow (in my list  :) )

**Comment by olragon** [comment]
Follow #418
