### ISSUE TITLE
App Suggestion: OnlyOffice

### ISSUE THREAD

**Issue by Ratatinator97** [caprover/one-click-apps#401]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
https://www.onlyoffice.com/

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/onlyoffice/documentserver

**Comment by Ak4zh** [comment]
Whoever picks this, please refer to 

https://help.nextcloud.com/t/onlyoffice-removed-web-mobile-editing-from-version-5-5-0-of-community-document-server/74360

https://github.com/ONLYOFFICE/DocumentServer/issues/805

Unlocked Version:
https://github.com/Zegorax/OnlyOffice-Unlimited

**Comment by Ratatinator97** [comment]
#423 was merged 👌 Closing this issue
