### ISSUE TITLE
App Suggestion: nocodb

### ISSUE THREAD

**Issue by eliagentili** [caprover/one-click-apps#436]
Hi there,
I don't have the competencies to that by myself, but I want to suggest integrating this (IMHO) amazing project:
[https://github.com/nocodb/nocodb](https://github.com/nocodb/nocodb)

It's an open-source project that emulates AirTable, and I think it can add real value to the CapRover community.

I don't know if there is an official Docker image for this app.

Thank You all in advance!

**Comment by christophemarois** [comment]
Added in https://github.com/caprover/one-click-apps/pull/437#issue-659592964
