### ISSUE TITLE
Recipe error for openldap

### ISSUE THREAD

**Issue by FJLendinez** [caprover/one-click-apps#485]
Attending to the doc of [docker-openldap](https://github.com/osixia/docker-openldap#use-an-existing-ldap-database):

> [...] simply mount this directories as a volume to /var/lib/ldap and /etc/ldap/slapd.d

In this case, [the yml provided](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/phpldapadmin.yml) for OpenLDAP + phpldapadmin only mount `/var/lib/ldap`, causing an error when you restart the container.

I test on my machine changing the volumes like this and it works. 
```
        volumes:
            - $$cap_appname-db:/var/lib/ldap
            - $$cap_appname-config:/etc/ldap/slapd.d

**Comment by githubsaturn** [comment]
Fixed! Thank you!
