### ISSUE TITLE
Update MinIO one-click-app

### ISSUE THREAD

**Issue by italodeandra** [caprover/one-click-apps#486]
I'm currently receiving this message:

```
2021-09-03T06:50:00.594856349Z You are running an older version of MinIO released 6 months ago
2021-09-03T06:50:00.594862744Z Update: Run `mc admin update`
```

I tried to update myself by using a newer image, but the current one-click-app configuration is so outdated that it doesn't know that we now need to use an argument for setting the port for the console.
The default port for the console is random, so I can't even change the `Container HTTP Port`.

Sadly, this argument is not an environment variable.

**Comment by githubsaturn** [comment]
Please see here: https://github.com/caprover/one-click-apps/issues/479

One click apps are community maintained. Feel free to open a PR.

**Comment by italodeandra** [comment]
Hey, I don't have experience with that stuff and I'm a little bit clustered by tasks. I'll close this issue for now and keep using the old version while keeping an eye on the issue you linked. Thanks.
