### ISSUE TITLE
BUG: Website results in 404

### ISSUE THREAD

**Issue by kaaax0815** [caprover/one-click-apps#487]
I want to use `https://oneclickapps.caprover.com/` but I only get `404 - File not found`

**Comment by githubsaturn** [comment]
The website doesn't have anything at the root. What do you want to use it for?

By default, it is already integrated in your CapRover installation and you're getting all one click apps in your CapRover instance.

![Screenshot from 2021-09-05 08-44-57](https://user-images.githubusercontent.com/10582082/132132926-416fdb22-e731-4201-9cca-7f8c71adf6f2.png)

**Comment by githubsaturn** [comment]
For example, MySQL is at `https://oneclickapps.caprover.com/v4/apps/mysql`

**Comment by kaaax0815** [comment]
I thought based on https://github.com/caprover/one-click-apps#build-your-own-one-click-app-repository it means that there is proper a website. with e.g. a page with all apps
And based on this https://github.com/caprover/one-click-apps/blob/976cf51092979d3fdfa49ea2578914f0628af5af/scripts/build_one_click_apps_from_v4.js#L19 i thought you get a json object/array with all oneclickapps

**Comment by githubsaturn** [comment]
http://oneclickapps.caprover.com/v4/list
