### ISSUE TITLE
Error using a newer version of Outline

### ISSUE THREAD

**Issue by Misly16** [caprover/one-click-apps#494]
Hi, trying to use a new version of Outline results in a small error. I made an issue in their repo (https://github.com/outline/outline/issues/2570) but maybe there's a possibility that it's an issue with how captover works?

**Comment by githubsaturn** [comment]
Outline OneClickApp is just technically a simple Docker Compose file: https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/outline.yml

There is nothing CapRover specific about it.


In general, when people contribute to one click apps, they test the latest version at the time and lock the docker compose to that version. 

There is no garauntee that the developers of each app make their apps compatible with future version. That's essentially why we always lock down the version that we have in our one click app definitions, and we discourage using `latest` tag.

https://github.com/caprover/one-click-apps/blob/master/.github/PULL_REQUEST_TEMPLATE.md
![image](https://user-images.githubusercontent.com/10582082/133695667-96dea920-8cee-42f7-973a-130d8b7e529e.png)

**Comment by githubsaturn** [comment]
Feel free to reopen if this is a CapRover issue.

**Comment by matbgn** [comment]
Fixed by #677
