### ISSUE TITLE
[Deployment Issue] Adguard Home: deploy failed request failed with status code 500

### ISSUE THREAD

**Issue by trfi** [caprover/one-click-apps#496]
I've been trying to install Adguard Home with one-click install and I've ran into an issue. Any one can help 😢
![2021-09-21_210332](https://user-images.githubusercontent.com/55879803/134185408-fd703828-808e-4476-8a79-dbbe065ef78e.jpg)
![2021-09-21_213734](https://user-images.githubusercontent.com/55879803/134191498-f1483e7c-3f7d-4f03-baf7-c0f44cb99133.jpg)

**Comment by trfi** [comment]
> Seems like your server fails to call registry-1.docker.io
> 
> Do you have a local firewall that could prevent this?
I think not
![2021-09-21_223402](https://user-images.githubusercontent.com/55879803/134201530-15ae36c7-8e8b-4190-a88e-8ffc40cbe544.jpg)

**Comment by githubsaturn** [comment]
Try running 
```
curl -v registry-1.docker.io
```

on your server. Does this work?

**Comment by trfi** [comment]
@githubsaturn 
Yes it working
![2021-09-22_100002](https://user-images.githubusercontent.com/55879803/134276777-51b146d3-19fd-4690-bda6-acea87ba4939.jpg)

**Comment by githubsaturn** [comment]
I'm at loss then. Is this only happening for AdGaurd? What about other one click apps?

**Comment by trfi** [comment]
@githubsaturn Other one click apps still working, just AdGuard. I tried

**Comment by githubsaturn** [comment]
Okay, then, you can manually pull adgaurd:
```
docker pull adguard/adguardhome:v0.104.3
```
Then try deploying the app.

**Comment by trfi** [comment]
@githubsaturn I ran to problem when run the container
`docker: Error response from daemon: driver failed programming external connectivity on endpoint adguardhome (17570576bfcf94d9a08c listen tcp4 0.0.0.0:3000: bind: address already in use.`

**Comment by trfi** [comment]
Issue was solved. Problem is systemd-resolved using port 53
