### ISSUE TITLE
App Suggestion: Calendso

### ISSUE THREAD

**Issue by nileshtrivedi** [caprover/one-click-apps#519]
[Calendso](https://cal.com/) is AGPL-licensed self-hostable alternative to Calendly. [Here is their repo](https://github.com/calendso/calendso).

They already have a [Docker version](https://github.com/calendso/docker).

**Comment by matbgn** [comment]
We need to update this app. See https://cal.com/blog/calendso-rebrands-to-cal-com

And therefore the docker image https://hub.docker.com/r/calendso/calendso

**Comment by douglara** [comment]
Follow PR  https://github.com/caprover/one-click-apps/pull/854
