### ISSUE TITLE
Issue with Searx deployment

### ISSUE THREAD

**Issue by JOduMonT** [caprover/one-click-apps#548]
## ISSUE
[searx removed the checker](https://github.com/searx/searx-docker/pull/65)
Here the message I got when I tried to deployed the app

```
Deploying searx-checker (might take up to a minute)
Failed: Error: {"message":"pull access denied for searx/searx-checker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} pull access denied for searx/searx-checker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

#### with default TAG
![image](https://user-images.githubusercontent.com/5204724/139377079-a3454af4-ea6c-43be-825f-59e85ae04f2b.png)

#### with TAG latest
![image](https://user-images.githubusercontent.com/5204724/139377107-793b1561-ab75-445d-8c43-cde380cd30ea.png)

## SOLUTION
so that app should be updated ;)
[docker-compose.yml example](https://github.com/searx/searx-docker/blob/master/docker-compose.yaml)

**Comment by uhlhosting** [comment]
@JOduMonT let me know what you decide on between the above mentioned, I have started with caprover, also the competition looks good.

**Comment by JOduMonT** [comment]
I'm long time user of LinuxServer, and I want something more automated; Cloudron is awesome, but the price bother me when it comes to home selfhosting, that why I give a try to CapRover which is awesome because of the one-clicks-app and the FAQ it is able to digest docker-compose, so for now CapRover win, but I decided to look at k8s-at-home which is a different game with k3s. We will see, I'll probably comeback pass by ;)
Keep your great work it definitely fill a needs.
