### ISSUE TITLE
One Click Apps issues

### ISSUE THREAD

**Issue by uhlhosting** [caprover/one-click-apps#549]
Hi,

I have recently deployed Caprover, and tested some of the apps, like for example:

Uptime Kuma: https://stat.pac.uhl.cloud/dashboard
Fails with: Cannot connect to the socket server. [Error: websocket error] Reconnecting...

and 

Searx: Unable to deploy, template outdated, searx-console removed.

**Comment by githubsaturn** [comment]
Have you enabled websocker on the config page of your app?

**Comment by uhlhosting** [comment]
> Have you enabled websocker on the config page of your app?

Yes I did, for some reason it seems the container got killer after some time:

```
CONTAINER ID   IMAGE                              COMMAND                  LOCAL VOLUMES   SIZE      CREATED       STATUS                   NAMES
ebb3fccf2107   louislam/uptime-kuma:latest        "/usr/bin/dumb-init …"   1               0B        3 hours ago   Up 3 hours (healthy)     srv-captain--stat.1.whti7tfdahxq1m6n7pqwckkz3
c13eff7149b2   louislam/uptime-kuma:latest        "/usr/bin/dumb-init …"   1               0B        3 hours ago   Exited (0) 3 hours ago   srv-captain--stat.1.llpntysz5rqo6zrlhxala4b0x
```

**Comment by githubsaturn** [comment]
Containers restart when you click on Save&Update. That's expected.

But the fact that your Uptime Kuma is not working is weird. Did you use the default tag or did you change it?

I just deployed a test instance and it's working just fine: http://kuma.server.demo.caprover.com
credentials: `admin / captain42`

**Comment by uhlhosting** [comment]
I have use latest tag If  remember, anyhow it seems it all works just toke some time to recover.

**Comment by githubsaturn** [comment]
When a one click app is added to the official repo, the author is supposed to test a particular version. That's why we disallow usage of latest tag in the template. 

The reason is that the requirements might change in future versions. 

But yes, other than that, users can always test the latest tag and if it works, you can use it.
