### ISSUE TITLE
gitea - bug fix suggestion: package default version does't work with drone.io

### ISSUE THREAD

**Issue by DestinTech** [caprover/one-click-apps#559]
Problem: The current version of gitea is too old and doesn't include Oauth, causing drone.io to fail to authenticate presenting a  (404) error to the user.
Current version in One Click App: 1.7
Proposed change: 1.15.6

- The drone one-click app package requires gitea to be installed. 
- install 'gitea' and 'drone.io' 
- Set up gitea, log in
- You are unable to complete the following setup requirement in the drone.io package due to the old version of gitea.

"_You must generate an OAuth2 application in Gitea (Settings->Applications->Create a new OAuth2 Application) with the "Redirect URI" https://<your drone server>/login. Make a note of the Client ID and the Client Secret and use them in the appropriate fields below._"

**Comment by githubsaturn** [comment]
One click apps are community maintained. Please feel free to edit, test and create a PR.

**Comment by DestinTech** [comment]
> One click apps are community maintained. Please feel free to edit, test and create a PR.

Please link the following PR:
https://github.com/caprover/one-click-apps/pull/561 

Thank you!
