### ISSUE TITLE
Update issue template

### ISSUE THREAD

**Issue by Ak4zh** [caprover/one-click-apps#567]
Please update the issue template as below so people who create app suggestion issue does provide more detailed info for suggested app like app logo, git repo etc to make it easy for anyone wanting to add the app.

**Please provide following details for the app you want to see on CapRover as a one-click app.**

**App Name:** 
**App Description:**

**References:**
- Git repo url: 
- App Logo url in png format (required): 
- Official website (optional): 
- Link to Dockerfile (if available): 
- Link to Docker Compose (if available): 
- Link to Docker hub (if available): 

**Comments:** 
If you have already tried to run the app using TEMPLATE_ONE_CLICK_APP and it failed, please add your findings here.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/suggestion.md

Good suggestions! Feel free to edit this file.
