### ISSUE TITLE
Issue in installing one click app (Seafile, no-memcache)

### ISSUE THREAD

**Issue by asitav-sen** [caprover/one-click-apps#582]
Hi,
Thank you for the great work. I am facing some issues in installing some one click apps.
The app log for seafile shows the following
`subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-8.0.7/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 255.`

Can you please help? Thanks!

**Comment by githubsaturn** [comment]
One click apps are community managed, feel free to comment on a more recent PR that updated your particular app. See here for example: https://github.com/caprover/one-click-apps/pull/522
