### ISSUE TITLE
Penpot

### ISSUE THREAD

**Issue by timconsidine** [caprover/one-click-apps#588]
Thanks so much for packaging this app.
It's awesome.

I am however having a problem with exporting to PDF/PNG/JPG/SVG
I have restarted the penpot-exporter container but it fails consistently : UNEXPECTED ERROR OCCURRED

Any thoughts on how to diagnose / resolve ?

**Comment by githubsaturn** [comment]
Hi @timconsidine  - one click apps are community maintained. For installation issues, feel free to find the PR that introduced the application and comment on the PR (e.g., [Penpot](https://github.com/caprover/one-click-apps/pull/398))

For other application questions, reach out to the application developer. you can see a similar issue here: https://github.com/penpot/penpot/issues/1050
