### ISSUE TITLE
App Suggestion: Caprover one-click apps public browser

### ISSUE THREAD

**Issue by 8byr0** [caprover/one-click-apps#618]
Hi there! 
I love caprover and have sometimes troubles following one-click apps updates.
If I want to know about new features/integrations I have to go to the repo, check for commits and finally get informations about it...

That being stated, I decided to make a simple browser scrapping all data from this repo and showing it in a nice way similar to the one embedded on my running instances:
![image](https://user-images.githubusercontent.com/21955112/152523218-6cac514a-1c0c-465f-9d2a-2f46eb64d545.png)

It shows apps created less than 4 weeks ago as "New" and allows to:
- search by name
- sort by name
- sort by last update
- sort by creation date

All the source code is available: here https://github.com/8byr0/caprover-sampleapps-browser
This is a gatsby website hosted on netlify [here](https://wizardly-ptolemy-8fcac8.netlify.app/).

Build are triggered using a changedetection.io instance (which I found while browsing one-click apps 😄) hosted using a caprover instance.

@githubsaturn if you'd want to provide a custom subdomain pointing on this that'd be great to make it useful for everyone (e.g. linking to it in the docs and this repo home page)

**Comment by githubsaturn** [comment]
Great work!
Added the link [here](https://caprover.com/docs/one-click-apps.html#other-apps)
