### ISSUE TITLE
[MongoDB] Cannot use mongo shell "[main] file [collections] doesn't exist failed to load:"

### ISSUE THREAD

**Issue by ekntrtmz** [caprover/one-click-apps#62]
Running Caprover from Digitalocean Marketplace and installed MongoDB as one-click-app. I tried to run some [mongo shell commands](https://docs.mongodb.com/manual/reference/mongo-shell/) e.g. `mongo show collections`. Unfortunately, there seems to be missing a file:

```
root@0ae15cf5a09b:/# mongo show collections
MongoDB shell version v4.0.9
connecting to: mongodb://127.0.0.1:27017/show?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("5f382f56-a1b7-424d-ab09-c518b9e941d1") }
MongoDB server version: 4.0.9
2019-05-19T11:46:27.373+0000 E -        [main] file [collections] doesn't exist
failed to load: collections
```

Is there a way to make shell commands for mongo run?

**Comment by githubsaturn** [comment]
First, I don't think you're using the shell command correctly. You shouldn't run `mongo show collections`, instead you should run:
```
mongo
######   Wait for the shell to attach, then run
show collections
```

Second, you'r not using your user/pass, therefore you're shell in unauthenticated. The correct form is:

```
mongo -u root -p mypassword
######   Wait for the shell to attach, then run
show dbs
show collections
.....
```


Third, CapRover is just a wrapper for official docker images. The best place to ask questions are official docker images repository. For MongoDB it's: https://github.com/docker-library/mongo
