### ISSUE TITLE
App issue: Penpot

### ISSUE THREAD

**Issue by githubber** [caprover/one-click-apps#628]
I've successfully installed Penpot. Thanks to all who made it possible.

It will really only be myself using it. How can I turn off registration? I figure it's a setting I can enter in App Configs, but I don't know the terms to use. Thank you!

**Comment by githubsaturn** [comment]
@githubber  - CapRover is simply an installation platform for the apps. We don't maintain the apps. Please reach out to the respective community.
https://github.com/penpot/penpot
