### ISSUE TITLE
App Suggestion: BitWarden

### ISSUE THREAD

**Issue by fr3fou** [caprover/one-click-apps#63]
I would like to see [BitWarden](https://bitwarden.com/) as a one-click app. It's an OSS password manager.

**Do you know if there is any official Docker image for the app?**

Yes, there is an image provided on their website.

**Comment by dg-otrs** [comment]
Yes would be awesome! Or Passbolt, this one is easier to setup.

**Comment by vohzd** [comment]
Bitwarden_rs is a lighter weight version. 

https://github.com/dani-garcia/bitwarden_rs/wiki

I'll see if I can get around to converting this into a one-click app

**Comment by githubsaturn** [comment]
Implemented by @vohzd

**Comment by LHz7ak** [comment]
Hi. Great work @vohzd. Thank you. Does anyone know how to change the default database to mysql using the caprover one click app ? I found this wiki but i don't know how to apply this in this case: https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend

Thanks

**Comment by vohzd** [comment]
Hello, from looking through the Dockerfile used by this image, it looks like it forces the use of SQL.
https://hub.docker.com/r/bitwardenrs/server/dockerfile

Seems like the best way to go is to fork this Dockerfile and specify MySQL + add in an variable for the Database URL that'll be your MySQL server. 

Caprover's UI will allow you to paste a straight Dockerfile in and you can also pass through any argument you define under the 'App Config' bit with ${YOUR_VAR}. For example;

`ARG DATABASE_URL = ${WHATEVER_ITS_CALLED_IN_THE_GUI}`
