### ISSUE TITLE
App Suggestion: [Appwrite]

### ISSUE THREAD

**Issue by SOG-web** [caprover/one-click-apps#633]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

AppWrite
**Do you know if there is any official Docker image for the app?**

Yes

docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.13.0

Thanks in Advance

**Comment by danielrataj** [comment]
Pull request #638 adds Appwrite to the Caprover. 🍀

**Comment by SOG-web** [comment]
wow, has it been added
