### ISSUE TITLE
App Suggestion: RocketChat

### ISSUE THREAD

**Issue by fr3fou** [caprover/one-click-apps#66]
**Please tell us what app you'd like to see on CapRover as a one-click app.**

https://github.com/RocketChat/Rocket.Chat
https://rocket.chat/

**Do you know if there is any official Docker image for the app?**

Yes, https://hub.docker.com/r/rocketchat/rocket.chat/

**Comment by dg-otrs** [comment]
Hey,

here some infos to deploy rocketchat with a mongodb replica cluster:

# Caprover settings **Chat**
image/captain-definition:
github.com/dg-otrs/rocket-chat master

App details:
Enable HTTPS
Force HTTPS
Port 3000
Websocket yes

ENV:
MONGO_URL=mongodb://rocketchat:xxx@srv-captain--mongodb:27017/rocketchat
MONGO_OPLOG_URL=mongodb://rocketchat:xxx@srv-captain--mongodb:27017/local?replSet=rs0&authSource=admin

Persistent data:
/app rocketchat

# Caprover settings **DB**
Image:
github.com/dg-otrs/mongodb master

App details:
Do not expose
Setup a replica cluster with arbiter and secondary node, this means 3 separate mongodb instances see ENV for details

ENV **mongodb**:
MONGO_INITDB_ROOT_USERNAME=root
MONGODB_ROOT_PASSWORD=xxx
MONGO_INITDB_ROOT_PASSWORD=xxx
MONGODB_EXTRA_FLAGS=--oplogSize=128 --enableMajorityReadConcern=false
MONGODB_REPLICA_SET_MODE=primary
MONGODB_ADVERTISED_HOSTNAME=srv-captain--mongodb
MONGODB_REPLICA_SET_KEY=key123
MONGODB_PRIMARY_PORT_NUMBER=27017

ENV **mongodb arbiter**:
MONGODB_ADVERTISED_HOSTNAME=srv-captain--mongodb-arbiter
MONGODB_REPLICA_SET_MODE=arbiter
MONGODB_PRIMARY_HOST=srv-captain--mongodb
MONGODB_PRIMARY_PORT_NUMBER=27017
MONGODB_PRIMARY_ROOT_PASSWORD=xxx
MONGODB_REPLICA_SET_KEY=key123

ENV **mongod secondary**:
MONGODB_ADVERTISED_HOSTNAME=srv-captain--mongodb-secondery
MONGODB_REPLICA_SET_MODE=secondary
MONGODB_PRIMARY_HOST=srv-captain--mongodb
MONGODB_PRIMARY_PORT_NUMBER=27017
MONGODB_PRIMARY_ROOT_PASSWORD=xxx
MONGODB_REPLICA_SET_KEY=key123

Persistent data:
/bitnami mongodb


# docu
https://rocket.chat/docs/installation/manual-installation/mongo-replicas/
https://hub.docker.com/r/bitnami/mongodb/
https://hub.docker.com/_/rocketchat

# prepare mongodb

# Login with bash into DB container
docker exec -it XXX bash

mongo --username root --password xxx
rs0:PRIMARY> 
use rocketchat
db.movie.insert({"name":"tutorials point“})
db.createUser(
  {
    user: "rocketchat",
    pwd:  "xxx",
    roles: [ { role: "readWrite", db: "rocketchat" },
             ]
  }
)

use admin
db.createUser(
  {
    user: "rocketchat",
    pwd:  "xxx",
    roles: [ { role: "readWrite", db: "local" }
             ]
  }
)

**Comment by ckc** [comment]
+1

Look forward to add it in one-click

**Comment by dg-otrs** [comment]
I'm more or less than with RC as one click app. 

The only thing missing is the setup of replica set of the mongo db: rs.inistate()

currently a manual task, via:
docker exec -it xxx bash

# prepare mongodb
mongo --username root --password

**Comment by dg-otrs** [comment]
> I'm more or less than with RC as one click app.
> 
> The only thing missing is the setup of replica set of the mongo db: rs.inistate()
> 
> currently a manual task, via:
> docker exec -it xxx bash
> 
> prepare mongodb
> mongo --username root --password

So if someone has an idea...

I'm using the bitnami mongo db image, with MONGODB_EXTRA_FLAGS: 
--oplogSize=128 --enableMajorityReadConcern=false  --smallfiles --replSet=rs01

But the replset is not there, until I do it manually. see above

**Comment by cbmalstic** [comment]
looking forward to this feature

**Comment by adolfombarros** [comment]
looking forward to this feature

**Comment by nileshtrivedi** [comment]
I believe one approach can be to package Rocket Chat without the database, similar to Wordpress. Then it can connect to existing MongoDB install within CapRover and does not need to run this db preparation script.

**Comment by johncrisp** [comment]
Hi 

I'm John, Community Manager at Rocket.Chat

 So how can we help? Someone asked in our #support channel.

Late for me now so I'll take a look tomorrow.

You can get me at https://open.rocket.chat as john.crisp if you want to chat.

I can setup a channel or team there if you need somewhere to liaise as we want help projects like this, and we can get some of our devs to help if needs be.

**Comment by mdehollander** [comment]
I would also love to see rocket chat supported in caprover :). I haven't look at this recipe in detail, but I think the replication of mongodb is the bottleneck. Can rocket chat also work with a single database instance? @johncrisp, great if some of the rc devs can help out here.

**Comment by mdehollander** [comment]
Maybe the configuration of the Rocket Chat app for The Coop Cloud can help: https://git.coopcloud.tech/coop-cloud/rocketchat/src/branch/main/compose.yml#L73 The Coop Cloud is a similar project that also uses the Docker Compose specification for it's apps: https://docs.coopcloud.tech/faq/#why-use-the-compose-specification

**Comment by debdutdeb** [comment]
Hello everyone ! (except John, you see me everyday :p) 👋🏼 

I'm the Deployment Specialist at Rocket.Chat

> Can rocket chat also work with a single database instance?

Yes. You just need to initiate the replicaset, no need for an arbiter or secondary. Surely you can add them later if you want/need to scale. Most of our existing deployment methods - e.g. snaps, docker - use a single node mongo resplicaset.

```
rs.initiate({
    _id: 'rs0',
    members: [ { _id: 0, host: 'localhost:27017' } ]
})
```

We'd love to see Rocket on as many platforms as possible! At least I know I do :p 

As John said, please **do not** hesitate to contact us on Open - debdut.chakraborty - I know, not the easiest - but you'll see me lurking in the #support, #ubuntu-snap and many other places. 

In the meantime, I'll look into this more in detail. I do have some platforms/methods in priority queue this quarter - so I don't know if I can promise anything. But since John himself sent me this link, it has now become important 🍷 

Again, come to our open server! We'd love to have a chat 😉

**Comment by aaron5670** [comment]
Looking forward 😃

**Comment by andrekutianski** [comment]
I almost get running Rocket.Chat on Caprover, but the only issue is the MongoDB replica set that requires some additional [commands](https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml#L47) not supported on the Caprover file definition.

From my understanding of this threat, a post-command will possible to define the replica command?

**Comment by githubsaturn** [comment]
@andrekutianski  - there are a few ways to get around this limitation on CMD.

1- You can embedded in as a Dockerfile line, like this: https://github.com/caprover/one-click-apps/blob/48d2870e6e5769acce66a4a14712968f347683bf/public/v4/apps/chatwoot.yml#L39-L44


2- More complex: you can have a note after installation asking users to copy paste this content into their [service override](https://caprover.com/docs/service-update-override.html) of their MongoDB:
```
TaskTemplate:
  ContainerSpec:
    Command:
      - "echo 1 && sleep 10m"
```

**Comment by debdutdeb** [comment]
Hey everyone, just a heads up, I believe I forgot to update it here. I will be opening a PR by the end of this month (worst case scenario). Rocketchat will be available in caprover very soon. 

I'm currently making changes to our docker image and compose file, simplifying it a bit more. After that change adding an one click template for caprover is not gonna be a problem anymore.

**Comment by JohnTrabusca** [comment]
@debdutdeb any eta when this will be available ? Thank you

**Comment by nileshtrivedi** [comment]
@debdutdeb Did you get a chance to prepare the docker/compose file and update the one-click template?

**Comment by nileshtrivedi** [comment]
I was able to reach @debdutdeb and he told me about the two PRs that have been raised in RocketChat repo and are being reviewed:

https://github.com/RocketChat/Rocket.Chat/pull/23426
https://github.com/RocketChat/Rocket.Chat/pull/23594

I (representing https://polyglot.network/ ) am offering a small bounty (55$) for packaging RocketChat as a one-click app for CapRover. I use RocketChat as an embedded chat room for https://learnawesome.org/ but not being available in CapRover means that I'm paying 5EUR/month for an additional server on Hetzner. I know 55$ is a very small amount but I hope this motivates somebody to submit a PR and close this issue. :-)

**Comment by waylon-gmail** [comment]
It is recommended to add a password to Mongo's configuration. After all, passwords are required in most cases.

**Comment by waylon-gmail** [comment]
It is recommended to add a password to Mongo's configuration. After all, passwords are required in most cases.
