### ISSUE TITLE
[Question] After each Strapi deployment database losts data

### ISSUE THREAD

**Issue by kwiat1990** [caprover/one-click-apps#660]
Hi guys, first of all, big thanks for your magnificent work!

On my Caprover instance I installed a Postgres one-click app, which I use to persist data of my Strapi instance. For Strapi I've created a custom `Dockerfile`, so I could use its the newest version. It looks like following (for brevity arguments were omitted):

```dockerfile
FROM node:16-alpine

ENV NODE_ENV production

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json /usr/src/app/
RUN npm ci

COPY . /usr/src/app

RUN npm run build
EXPOSE ${PORT}

CMD [ "npm", "start" ]
```

With that setup I can deploy everything to the server and everything just works. But as soon as I re-deploy Strapi all data stored in Postgres get lost and I don't quite understand why. I have also a `.dockerignore` file, which contains all files and directories that shouldn't be copied into image.
```
.tmp/
.cache/
.git/
build/
node_modules/
data/
```
This list is used by many other, so I think it should be OK. There's no other files/dirs in Strapi I would put on the ignore list.

Does anyone know the reason why all data in Postgres are being swept each time I deploy Strapi?

**Comment by githubsaturn** [comment]
Not sure what strapi does when you deploy a new version. But maybe they just erase the db? 

Also are you sure that your data is being stored in the postgres DB and not locally in tour strapi image?

**Comment by kwiat1990** [comment]
My Postgres is separate from Strapi, so it's not an issue. 

Perhaps the issue can be the fact, that I have change some collection types (add some), which have relations with the existing ones. After deployment Strapi can't deal with it because schema has changes and erase the data in the database to be able to work with the updated schema. I need to test that.
