### ISSUE TITLE
Healthchecks app typo

### ISSUE THREAD

**Issue by Focus3D** [caprover/one-click-apps#666]
HIi,
There is a typo on password variable id  [https://github.com/caprover/one-click-apps/blob/39577b1ea66c0e9c30143a786a1a1bf15dff97bb/public/v4/apps/healthchecks.yml#L39](https://github.com/caprover/one-click-apps/blob/39577b1ea66c0e9c30143a786a1a1bf15dff97bb/public/v4/apps/healthchecks.yml#L39)

 `$$cap__postgres_password` should be  `$$cap_postgres_password`  remove extra underscore

**Comment by sandrohanea** [comment]
Hello!
The one-click-apps are community maintained and everyone can submit PRs. I created a PR to fix this typo.
