### ISSUE TITLE
App Suggestion: SearXNG

### ISSUE THREAD

**Issue by Schiriki123** [caprover/one-click-apps#681]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
SearXNG: A fork of Searx.
Even though Searx is already available, the [docker repository](https://github.com/searx/searx-docker) isn't developed anymore (but the docker hub is still being updated :thinking:)
and SearXNG supports arm architectures.

**Do you know if there is any official Docker image for the app?**
https://github.com/searxng/searxng-docker

**Comment by Qubitspm** [comment]
You can already use SearXNG. i use it too. Just install the included searx and edit the freshly installed searx. Insert the SearXNG github link under the Deployment tab and click Upload/Deploy.
