### ISSUE TITLE
Changing urls in iredmail

### ISSUE THREAD

**Issue by kendofriendo** [caprover/one-click-apps#700]
As it stands, when you install and enter mail.domain.com, mail.domain.com will actually direct you to the *admin* login for iredmail. The actual webmail login is at mail.domain.com/mail. I'd like to change this so that mail.domain.com takes you to the webmail login and mail.domain.com/admin or mail.domain.com/mail takes you to the admin login.

I can't parse where I can edit these options in the configs.

**Comment by ido-pluto** [comment]
This is the local Ngnix configuration, right now there is not easy way to to edit that.
You can connect to the docker container and edit the files at 
`/etc/nginx/sites-conf.d/default-ssl`
