### ISSUE TITLE
App Suggestion: [ODOO]

### ISSUE THREAD

**Issue by oda-alexandre** [caprover/one-click-apps#71]
**odoo**
- site web : https://www.odoo.com
- Docker official : https://hub.docker.com/_/odoo/

thank you for your work

**Comment by abedev31** [comment]
hi all see below a template with the odooV12.0 & postgres, enjoy it :)

{
    "captainVersion": "2",
    "documentation": "https://github.com/caprover/one-click-apps",
    "dockerCompose": {
        "version": "3.3",
        "services": {
            "$$cap_appname-db": {
                "image": "postgres:$$cap_postgres_version",
                "notExposeAsWebApp": "true",
                "volumes": [
                    "$$cap_appname-db-data:/var/lib/postgresql/data"
                ],
                "restart": "always",
                "environment": {
                    "POSTGRES_USER": "odoo",
                    "POSTGRES_PASSWORD": "$$cap_pg_pass",
                    "POSTGRES_DB": "postgres"
                }
            },
            "$$cap_appname": {
                "image": "odoo:12.0",
                "containerHttpPort": "8069",
                "depends_on": [
                    "$$cap_appname-db"
                ],
                "volumes": [
                    "odoo-web-data:/var/lib/odoo",
                    "config:/etc/odoo",
                    "addons:/mnt/extra-addons"
                ],
                "restart": "always",
                "environment": {
                    "POSTGRES_PASSWORD": "$$cap_pg_pass",
                    "HOST": "srv-captain--$$cap_appname-db"
                }
            }
        }
    },
    "networks": {
        "db": {
            "driver": "bridge"
        },
        "search": {
            "driver": "bridge"
        }
    },
    "instructions": {
        "start": "Odoo is an open source product CRM",
        "end": "Odoo is deployed and available as srv-captain--$$cap_appname:8069 to other apps."
    },
    "variables": [
        {
            "id": "$$cap_postgres_version",
            "label": "Postgres Version",
            "defaultValue": "11.1",
            "description": "Checkout their docker page for the valid tags https://hub.docker.com/r/library/postgres/tags/",
            "validRegex": "/^([^\\s^\\/])+$/"
        },
        {
            "id": "$$cap_pg_pass",
            "label": "Postgres Password",
            "description": "",
            "validRegex": "/.{1,}/"
        },
        {
            "id": "$$cap_pg_initdb_args",
            "label": "OPTIONAL: Arguments for 'postgres initdb'",
            "description": "For example, --data-checksums",
            "validRegex": "/.{0,}/"
        }
    ]
}

**Comment by oda-alexandre** [comment]
thank you very much

**Comment by jacquant** [comment]
I made the PR #212  from @abedev31's template, thx.

**Comment by carlosbernabeujuan** [comment]
Hi team! Thanks for the work! I'm getting this error today:

![Screenshot 2023-06-15 at 14 04 12](https://github.com/caprover/one-click-apps/assets/17138730/6416ca61-219e-49f1-8917-5d34b2b9ae0e)


Any help is appreciated

**Comment by githubsaturn** [comment]
Get your server logs to see what's going on. The app registration failing indicates something is wrong with your server. It's before the one click app is deployed
