### ISSUE TITLE
App Suggestion: GetLago

### ISSUE THREAD

**Issue by TarekMahran** [caprover/one-click-apps#739]
Can Any one Support Adding the below App to Caprover One click apps?

Open Source Billing API for Product-Led SaaS

https://github.com/getlago/lago

Docker compose file here:
https://github.com/getlago/lago/blob/main/docker-compose.arm64.yml

**Comment by ronaldloyko** [comment]
Nice app! I will add it.

**Comment by stepcellwolf** [comment]
@ronaldloyko thanks for adding this app, indeed.
However, I'm having an issue when I try to Enable HTTPS for a dashboard, I get the following error:
`1107 : Verification Failed.`

I was able to enable it for API and the rest, but not for the dashboard URL. 

Tried several suggestions, but nothing worked out. 
Could you please help me out?

**Comment by stepcellwolf** [comment]
No worries, managed to fix it with this [solution](https://github.com/caprover/caprover/issues/600).
