### ISSUE TITLE
App Suggestion: pocketbase

### ISSUE THREAD

**Issue by hAhl2** [caprover/one-click-apps#785]
[Open Source backend
for your next SaaS and Mobile app
in 1 file](https://pocketbase.io/)

**Do you know if there is any official Docker image for the app?**
here is a thread, https://github.com/pocketbase/pocketbase/issues/92

**Comment by wzulfikar** [comment]
@hAhl2 Pocketbase is available since Oct 2022.

See https://github.com/caprover/one-click-apps/pull/769
