### ISSUE TITLE
App Suggestion:  Meilisearch

### ISSUE THREAD

**Issue by hermesalvesbr** [caprover/one-click-apps#788]
An open-source, lightning-fast, and hyper-relevant search engine that fits effortlessly into your apps, websites, and workflow.

A opensource alternative to Algolia. 

**Do you know if there is any official Docker image for the app?**

https://docs.meilisearch.com/learn/cookbooks/docker.html

**Comment by githubsaturn** [comment]
It's already available: https://github.com/caprover/one-click-apps/pull/409
