### ISSUE TITLE
App Suggestion: Poste.io

### ISSUE THREAD

**Issue by devxpy** [caprover/one-click-apps#80]
Hey there!

I was trying to get [poste.io](https://poste.io/doc/) working, and saw 2 red-flags in their Web UI. 

```json
{
  "captainVersion": "1",
  "dockerCompose": {
    "version": "3.7",
    "services": {
      "$$cap_appname": {
        "image": "analogic/poste.io",
        "ports": [
          "25:25",
          "110:110",
          "143:143",
          "465:465",
          "587:587",
          "993:993",
          "995:995",
          "4190:4190"
        ],
        "volumes": [
          "/etc/localtime:/etc/localtime:ro",
          "$$cap_appname-data:/data",
          "/captain/generated/static/domains/$$cap_host/.well-known:/opt/www/.well-known."
        ],
        "restart": "always",
        "environment": {
          "HTTPS": "OFF",
          "LETSENCRYPT_EMAIL": "$$cap_email",
          "LETSENCRYPT_HOST": "$$cap_host",
          "VIRTUAL_HOST": "$$cap_host"
        }
      }
    }
  },
  "instructions": {
    "start": "SMTP + IMAP + POP3 + Antispam + Antivirus\nWeb administration + Web email\n...on your server in ~5 minutes\n\nRecommended: Use\"mail\" as the App Name.",
    "end": "Poste is deployed and available as $$cap_appname. \n\n IMPORTANT: It will take up to 2 minutes for Poste to be ready. Before that, you might see 502 error page.\n"
  },
  "variables": [
    {
      "id": "$$cap_email",
      "label": "Email Address",
      "description": "The email address used for Lets Encrpt certificates."
    },
    {
      "id": "$$cap_host",
      "label": "Hostname",
      "description": "The full hostname for this captain app. (usually mail.mydomain.com)"
    }
  ]
}
```

Could you please guide me on how I can solve these 2 issues?

![image](https://user-images.githubusercontent.com/19492893/61821282-6d051600-ae74-11e9-899e-6412f0ede961.png)

It seems like poste.io requires the `--hostname` argument to work, and caprover ignores that in docker-compose.

Not sure what the Let's encrypt warning is about.

**Comment by devxpy** [comment]
Note: Mail send/receive works fine even with these warnings :)

**Comment by githubsaturn** [comment]
This question would be more appropriate for poste.io.

For Let'sEncrypt, I am unsure how they perform the challenge, but in CapRover system, all apps are behind nginx router, the HTTPS certs are being managed by CapRover.

For the other IP problem, it's because the request the intercepted by nginx. It's technically a bug in poste.io as they need to account for the routing layer. Not all installations sit without a routing layer.

**Comment by ComputerCarl** [comment]
@devxpy I'd like to install this. Could you post when you get a resolution? Have you been getting issues with the "Mailserver will not work correctly in multiple aspects."?

**Comment by devxpy** [comment]
Not really. My emails have been going to spam, but I doubt that has anything to do with this specifically.

**Comment by devxpy** [comment]
A small change allows for let's encrypt ACME challenge to function.

```json
{
  "captainVersion": "1",
  "dockerCompose": {
    "version": "3.7",
    "services": {
      "$$cap_appname": {
        "image": "analogic/poste.io",
        "ports": [
          "25:25",
          "110:110",
          "143:143",
          "465:465",
          "587:587",
          "993:993",
          "995:995",
          "4190:4190"
        ],
        "volumes": [
          "/etc/localtime:/etc/localtime:ro",
          "$$cap_appname-data:/data",
          "/captain/generated/static/domains/$$cap_host/.well-known/acme-challenge:/opt/www/.well-known/acme-challenge"
        ],
        "restart": "always",
        "environment": {
          "HTTPS": "OFF",
          "LETSENCRYPT_EMAIL": "$$cap_email",
          "LETSENCRYPT_HOST": "$$cap_host",
          "VIRTUAL_HOST": "$$cap_host"
        }
      }
    }
  },
  "instructions": {
    "start": "SMTP + IMAP + POP3 + Antispam + Antivirus\nWeb administration + Web email\n...on your server in ~5 minutes\n\nRecommended: Use\"mail\" as the App Name.",
    "end": "Poste is deployed and available as $$cap_appname. \n\n IMPORTANT: It will take up to 2 minutes for Poste to be ready. Before that, you might see 502 error page.\n"
  },
  "variables": [
    {
      "id": "$$cap_email",
      "label": "Email Address",
      "description": "The email address used for Lets Encrpt certificates."
    },
    {
      "id": "$$cap_host",
      "label": "Hostname",
      "description": "The full hostname for this captain app. (usually mail.mydomain.com)"
    }
  ]
}
```

However, this required me to manually do 

```
$ mkdir /captain/generated/static/domains/mail.mydomain.com/.well-known/acme-challenge
```

@githubsaturn Is there any way to automate this `mkdir` command?

**Comment by githubsaturn** [comment]
As I mentioned above, SSL certs are being managed by CapRover. Specifically, `/.well-known/` directory for each app is being managed by CapRover. Note that it's inside the `generated` directory. As the name suggests, the content are being generated by CapRover and you should not modify it. In fact, the entire `generated` directory gets deleted and repopulated on every server restart.


This might work as a temporary work around, but it's not a solid solution. If you need to have access to the SSL certs. You should:
- Enable HTTPS for your app. At this point, CapRover (via LetsEncrypt) generates the SSL certs.
- Find the generated SSL certs and and map them as a volume to your Poste.io app. 
- SSL certs are stored in this directory:
```
/captain/data/letencrypt/etc/live#
```

**Comment by devxpy** [comment]
It looks like the emails are delivered just fine to a gmail inbox, even with the LetsEncrpyt ACME test disabled.
(HTTPS enabled and enforced in caprover)

I'll issue a pull request since I was able to make this work. 

---

The trick to not getting marked as spam is to properly set up the reverse DNS for your server, DKIM, and SPF records.

**Comment by valoricDe** [comment]
When my mail client connects to poste.io it says the poste certificate does not match the hostname. So I created multiple volumes following @githubsaturn 's suggestions:
```
/captain/data/letencrypt/etc/live/mail.valoric.de/chain.pem -> /data/ssl/ca.crt
/captain/data/letencrypt/etc/live/mail.valoric.de/cert.pem -> /data/ssl/server.crt
/captain/data/letencrypt/etc/live/mail.valoric.de/privkey.pem -> /data/ssl/server.key
```
I don't know what will happen when caprover refreshes the certificate but the poste server is not restarted. Would be theoretically a way that caprover restarts the service on certificate renewal?

**Comment by githubsaturn** [comment]
@valoricDe CapRover doesn't restart the services when the certs are renewed. In fact, certs are checked once a day and will be renewed if possible by [Certbot](https://certbot.eff.org/). However, CapRover doesn't receive a callback whether or not the certs were renewed. It's the job of application to refresh its cache.

If poste.io isn't doing this automatically, you can setup a cron job to restart the service every 20 days or so, by running
```
docker service update srv-captain--yourpostename --force
```

**Comment by Toninobandolero** [comment]
> When my mail client connects to poste.io it says the poste certificate does not match the hostname. So I created multiple volumes following @githubsaturn 's suggestions:
> 
> ```
> /captain/data/letencrypt/etc/live/mail.domain.de/chain.pem -> /data/ssl/ca.crt
> /captain/data/letencrypt/etc/live/mail.domain.de/cert.pem -> /data/ssl/server.crt
> /captain/data/letencrypt/etc/live/mail.domain.de/privkey.pem -> /data/ssl/server.key
> ```
> 
> I don't know what will happen when caprover refreshes the certificate but the poste server is not restarted. Would be theoretically a way that caprover restarts the service on certificate renewal?

Hi. Where exactly did you create that volumes in caprover?

**Comment by valoricDe** [comment]
If your app is called myapp at path `/#/apps/details/myapp
![Bildschirmfoto 2022-02-06 um 09 09 00](https://user-images.githubusercontent.com/22564188/152672617-94038beb-77b2-4973-b5f0-29f1115535ea.jpg)
`
