### ISSUE TITLE
minIO fails when enabling ssl `1107 : Verification Failed`

### ISSUE THREAD

**Issue by pcace** [caprover/one-click-apps#828]
Hi there, 

i am trying to install the minIO app. It failes with this error `1107 : Verification Failed.` when trying to enable ssl on the service. 
is there anything know to that problem or any idea what to do about it? Other apps do just fine with ssl.

Cheers and thanks for help!

<img width="644" alt="Bildschirm­foto 2023-01-04 um 12 39 44" src="https://user-images.githubusercontent.com/1011875/210547535-f8615bfc-898d-4cf7-931b-f12e9b12f43e.png">

**Comment by githubsaturn** [comment]
This is not related to minio. Read docs for more details on 1107, and how to resolve it:
https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

**Comment by pcace** [comment]
Guess it was related to https://github.com/caprover/caprover/issues/1631.
solved anyways
