### ISSUE TITLE
App issue: [Calendso]

### ISSUE THREAD

**Issue by djiworks** [caprover/one-click-apps#831]
READ FIRST:

### App bugs:
Image `calendso/calendso` is not more available on Docker Hub

### Installation bugs:
Deployement failed: 
```
Deploy failed!
Error: (HTTP code 404) unexpected - manifest for calendso/calendso:0.0.17-1 not found: manifest unknown: manifest unknown
```

Notes :
https://hub.docker.com/r/calendso/calendso : "calendso is now cal.com and moved to https://hub.docker.com/r/calcom/cal.com"
https://hub.docker.com/r/ctadeu/calendso/tags return 404

**Comment by githubsaturn** [comment]
ahh this is annoying, they keep changing their repo. It wasn't too long ago where a PR came in to support the "new" image:
https://github.com/caprover/one-click-apps/pull/796

 Anyways, I deleted the app from the app, but will ping the original contributor if they are interested in re-adding it:
@ak4zh 
https://github.com/caprover/one-click-apps/pull/394
