### ISSUE TITLE
App issue: Outline

### ISSUE THREAD

**Issue by nshkrsh** [caprover/one-click-apps#852]
Post installation, saw an instruction to run `npm run sequelize:migrate` in the docker container.
But the docker container keeps reinstalling with an error
```{"level":"warn","message":"Please` run `yarn db:migrate` or `yarn db:migrate --env production-ssl-disabled` to run all pending migrations"}```.
How to run the migration command?

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/215362003-abf60c3b-2b2f-433f-b8f9-2d13a2c31970.png)

**Comment by nshkrsh** [comment]
Because Caprover keeps restarting the docker machine due to the missing migration, I cannot run the migration script.
Can you please help me stop this auto-restart so I can SSH into the docker machine and run the migration script?

**Comment by githubsaturn** [comment]
CapRover does not restart the docker machine. I think you're referring to Docker container being restarted. That's done by Docker swarm. To stop that from happening, you need to go to app config > instance count and set it to zero. Then manually run the image. 

Keep in mind that CapRover is just a frontend tool on top of Docker swarm and on itself it does not manage the healthcheck and lifecycle of your containers.

**Comment by iamsid** [comment]
Tried installing Outline using one-click app as well. But could not get it to work.

I also tried installing using TEMPLATE option, with the YML file found in this issue: https://github.com/caprover/one-click-apps/pull/829, but still keep getting the migration error.

I don't understand docker too much, so not really sure how to "manually run the image" as explained above. I tried the command `docker run outlinewiki/outline:0.66.3` in SSH, but got an error related to ENV.

Don't think this is an Outline app issue, but just something is missing in Caprover one-click install configuration.

**Comment by aqidd** [comment]
Regarding Outline, AFAIK you need to run the migration outside caprover since this is what we've been doing several times. Outline doesn't handle live migration (migration while the app is running)

So you need to clone the repo to your local environment, set database path and run migration from your local computer before updating caprover
