### ISSUE TITLE
App issue: [Searx]

### ISSUE THREAD

**Issue by uhlhosting** [caprover/one-click-apps#872]
READ FIRST:

### App bugs:
For issues regarding an app (post installation), please report them in the related app forum. CapRover is simply an installation tool. Post installation bugs/issues should be redirected to the developer of the app.

### Installation bugs:
For issues regarding the installation of the app:
Search in the Pull Request section, and find the pull request where the one click app was added to the repo and ask the original contributor if they can provide any help.

CapRover core team cannot provide support for apps that are added by contributors.

Please Maintain/Update/Remove obsolete apps, the original uploader, should keep their apps, up to date, is nice to have a big list, if I go and test them, 30% of current app will not work. Meanwhile please remove/fix searx:

```Failed: Error: {"message":"pull access denied for searx/searx-checker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} pull access denied for searx/searx-checker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied```

**Comment by githubsaturn** [comment]
I removed searx, but please feel free to open PRs to remove any other non functional apps.

Feel free to open a PR and remove the apps.
