### ISSUE TITLE
App Suggestion: serpbear

### ISSUE THREAD

**Issue by jonas-hoebenreich** [caprover/one-click-apps#878]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
SerpBear is an Open Source Search Engine Position Tracking App. It allows you to track your website's keyword positions in Google and get notified of their positions.
https://github.com/towfiqi/serpbear

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/towfiqi/serpbear

**Comment by uhlhosting** [comment]
@jonas-hoebenreich have you managed to get serpbear running with GSC, and if so how you made the variables to use the. GCP private key  in one line?
