### ISSUE TITLE
App Suggestion: [Immich]

### ISSUE THREAD

**Issue by arthuragone** [caprover/one-click-apps#890]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Immich
https://immich.app/

**Do you know if there is any official Docker image for the app?**
I think so : https://immich.app/docs/install/docker-compose

**Comment by borjarobert** [comment]
I sent the PR so hopefully it gets added eventually https://github.com/caprover/one-click-apps/pull/893

**Comment by arthuragone** [comment]
> I sent the PR so hopefully it gets added eventually #893

Hi, I have no idea of what is a PR. I see you are working on it. Adapting the .yml seams plausible but how to manage the .env file?

Maybe you have guessed, but I am not familiar either with github contribution neither programming. I selfhost with Caprover as a maximum to my competance.

**Comment by borjarobert** [comment]
Working on it. Caprover provides enough to adapt the contents of the .env file. I'm currently testing that everything is fine. I sent a what I thought was a good .yml (which wasn't) and should be able to send a proper one for consideration very soon.

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/pull/894
