### ISSUE TITLE
App issue: [Minio - missing environment variable value]

### ISSUE THREAD

**Issue by paluigi** [caprover/one-click-apps#895]
I am a beginner with Caprover, please help me to provide more information if the below is not enough.

After installing the Minio One Click app I complete the two actions listed:
- Enable HTTPS
- Enable websockets

In order to login in the web console I need to update the CLIENT_MAX_BODY_SIZE environment variable inside the -api app, else I receive the following error when I try to login:
`Expected element type <Error> but have <html>`

After updating the environment variable, web login and client login work. How can this variable be automatically set (or how can we put an alert for users to set it)? 

Thanks,
Luigi

**Comment by githubsaturn** [comment]
As mentioned [here](https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md), please file issues with specific apps on the relevant PRs. CapRover one click apps are community maintained.

PR that added client max body size:
https://github.com/caprover/one-click-apps/pull/858
