### ISSUE TITLE
App Suggestion: pgbackup

### ISSUE THREAD

**Issue by leeroyOV** [caprover/one-click-apps#923]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
pgbackup - Docker container that can backup postgres containers to a mounted /backups volume

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/oostvoort/pgbackup
https://github.com/oostvoort/pgbackup

Link to app's One-Click YAML file
https://github.com/oostvoort/pgbackup/blob/main/oneclick.yml

**Comment by githubsaturn** [comment]
Looks like this app doesn't fit our criteria for the official repo:
![image](https://github.com/caprover/one-click-apps/assets/10582082/98fc5ec7-0d72-4746-9564-0a67a20ea7e6)
