### ISSUE TITLE
Deployement using bitbucket and Caprover is not working.

### ISSUE THREAD

**Issue by avaneeshtrana** [caprover/one-click-apps#930]
I have tries using SSH and HTTPS but I am getting Deploy failed error. 

I have tried using the SSH key and I am getting this error:
Build started for portal
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/admin-portal/665/source_files'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

When I try using username and password, I am getting this error:
Build started for admin-portal
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/admin-portal/664/source_files'...
remote: Login failed due to incorrect login credentials or method.
remote: If you are unsure of which login details or login method to use, visit:
remote: https://support.atlassian.com/bitbucket-cloud/docs/log-into-or-connect-to-bitbucket-cloud/
fatal: Authentication failed for 'https://ravaneeshthakur%40gmail.com:Avane%401@bitbucket.org/identify/portal/'

**Comment by githubsaturn** [comment]
Read this thread: https://github.com/caprover/caprover/issues/1265
