### ISSUE TITLE
App issue: [kutt] SITE_NAME doesn't have any effect

### ISSUE THREAD

**Issue by steigerdich** [caprover/one-click-apps#946]
Hey there,

I think there's a problem with the ENV. The provides SITE_NAME doesn't have any effect on my installation. The URL doesn't show up under _Terms of Service_. Furthermore I can't see any admin options in the settings when I register with my ADMIN_MAIL. 
Could you just check it?

Keep up your good work!
Thanks...

**Comment by githubsaturn** [comment]
![image](https://github.com/caprover/one-click-apps/assets/10582082/f5b26be2-9f94-46b1-ba92-8194cfe05409)

**Comment by githubsaturn** [comment]
Feel free to comment here: https://github.com/caprover/one-click-apps/pull/755
