### ISSUE TITLE
App Suggestion: activepieces

### ISSUE THREAD

**Issue by khairulimran-97** [caprover/one-click-apps#976]
https://www.activepieces.com/docs/install/options/docker

https://github.com/activepieces/activepieces

**Comment by atsepkov** [comment]
@khairulimran-97 were you able to deploy activepieces to your CapRover box? There is an option to install via github repo directly in caprover deploy tab, but when I try that I keep getting errors for some reason (I can't see the error itself, last line visible in the logs is: `npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs` which occurs a couple mins before the error that results in a rollback. Deploying locally via caprover CLI gives connection timeout/reset, which does not happen for other repos I already deployed the same way.

**Comment by githubsaturn** [comment]
I just look at the docker documentation and it's actually super simple to set up:

- Create a new app on CapRover (check the Persistent Data checkbox)
- Go to app config and add a new Persistent Directory: path: `/root/.activepieces` and label: `activepieces`
- Go to app config > env variables, and add these env variables:
```
AP_QUEUE_MODE=MEMORY
AP_DB_TYPE=SQLITE3
AP_FRONTEND_URL=http://localhost:8080
```
- Make sure you don't have any extra spaces, or typos in env var
- Click on Update & Save button to save the env vars
- Go to deployment tab, and under " Method 6: Deploy via ImageName  `activepieces/activepieces:0.10.1`
