### ISSUE TITLE
one click app ( emailengine ) resets occasianally

### ISSUE THREAD

**Issue by rinshadka** [caprover/one-click-apps#998]
Hi,

The one click app ( emailengine ) is resetting occasionally as  a fresh deployment and there by loosing the configurations and other changes I have made. Any idea on what might be the issue with and any hint how to proceed with the debugging.

Thanks.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![Uploading Screenshot_20231009-082814.png…]()

**Comment by githubsaturn** [comment]
![Screenshot_20231009-082814](https://github.com/caprover/one-click-apps/assets/10582082/6451df22-665e-4ef9-8b5d-af27a9a02f0a)
